/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;

import entity.Phong;
import gui.GD_DatPhong;
import dao.Phong_DAO;
import entity.LoaiPhong;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;
import javax.swing.JLabel;

/**
 *
 * @author PC BAO THONG
 */
public class Form_DatPhong extends javax.swing.JFrame {
    private Phong_DAO phongdao;
    /**
     * Creates new form FormDatPhong
     */
    public Form_DatPhong(Phong phong) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        updateTextField(phong);
    }
    private void updateTextField(Phong phong){
        phongdao = new Phong_DAO();
        txtSoPhong.setText(phong.getMaPhong());
        LoaiPhong lp =  phongdao.getLoaiPhongTheoMa(phong.getLoaiPhong().getMaLP());
        DecimalFormatSymbols symbols = new DecimalFormatSymbols(Locale.getDefault());
        symbols.setGroupingSeparator('.');
        DecimalFormat df = new DecimalFormat("#,##0.##", symbols);
        txtGiaTien.setText(""+df.format(lp.getGiaTien()) + " vnđ/giờ");
        txtSoNguoi.setText(phong.getSoNguoi()+"");
        txtLoaiPhong.setText(lp.getTenLoaiPhong());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelHeader = new javax.swing.JPanel();
        panelC = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblSoPhong = new javax.swing.JLabel();
        txtSoPhong = new javax.swing.JTextField();
        lblLoaiPhong = new javax.swing.JLabel();
        txtLoaiPhong = new javax.swing.JTextField();
        lblSoNguoi = new javax.swing.JLabel();
        txtSoNguoi = new javax.swing.JTextField();
        lblGiaTien = new javax.swing.JLabel();
        txtGiaTien = new javax.swing.JTextField();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        btnKiemTra = new javax.swing.JButton();
        lblTenKH = new javax.swing.JLabel();
        txtTenKhach = new javax.swing.JTextField();
        btnQuayLai = new javax.swing.JButton();
        btnDatPhong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setMaximumSize(new java.awt.Dimension(800, 40));
        panelHeader.setMinimumSize(new java.awt.Dimension(800, 40));
        panelHeader.setPreferredSize(new java.awt.Dimension(800, 40));
        panelHeader.setLayout(new java.awt.GridLayout(1, 0));

        panelC.setBackground(new java.awt.Color(121, 188, 215));
        panelC.setPreferredSize(new java.awt.Dimension(170, 30));
        panelC.setLayout(new java.awt.GridBagLayout());

        lblTittle.setBackground(new java.awt.Color(255, 255, 255));
        lblTittle.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(33, 36, 71));
        lblTittle.setText("ĐẶT PHÒNG");
        lblTittle.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panelC.add(lblTittle, new java.awt.GridBagConstraints());

        panelHeader.add(panelC);

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 460));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 460));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 460));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 15, 0, 15, 0, 15, 0, 15, 0};
        jPanel1Layout.rowHeights = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0};
        jPanel1.setLayout(jPanel1Layout);

        lblSoPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblSoPhong.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblSoPhong.setText("Số phòng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(lblSoPhong, gridBagConstraints);

        txtSoPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSoPhong.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSoPhong.setEnabled(false);
        txtSoPhong.setMinimumSize(new java.awt.Dimension(150, 40));
        txtSoPhong.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtSoPhong, gridBagConstraints);

        lblLoaiPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblLoaiPhong.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblLoaiPhong.setText("Loại phòng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(lblLoaiPhong, gridBagConstraints);

        txtLoaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLoaiPhong.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtLoaiPhong.setEnabled(false);
        txtLoaiPhong.setMinimumSize(new java.awt.Dimension(150, 40));
        txtLoaiPhong.setPreferredSize(new java.awt.Dimension(200, 40));
        txtLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiPhongActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(txtLoaiPhong, gridBagConstraints);

        lblSoNguoi.setBackground(new java.awt.Color(255, 255, 255));
        lblSoNguoi.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblSoNguoi.setText("Số người");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(lblSoNguoi, gridBagConstraints);

        txtSoNguoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSoNguoi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtSoNguoi.setEnabled(false);
        txtSoNguoi.setMinimumSize(new java.awt.Dimension(150, 40));
        txtSoNguoi.setPreferredSize(new java.awt.Dimension(200, 40));
        txtSoNguoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoNguoiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel1.add(txtSoNguoi, gridBagConstraints);

        lblGiaTien.setBackground(new java.awt.Color(255, 255, 255));
        lblGiaTien.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblGiaTien.setText("Giá tiền");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(lblGiaTien, gridBagConstraints);

        txtGiaTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtGiaTien.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtGiaTien.setEnabled(false);
        txtGiaTien.setMinimumSize(new java.awt.Dimension(170, 40));
        txtGiaTien.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        jPanel1.add(txtGiaTien, gridBagConstraints);

        lblSDT.setBackground(new java.awt.Color(255, 255, 255));
        lblSDT.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblSDT.setText("SĐT Khách");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(lblSDT, gridBagConstraints);

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSDT.setMinimumSize(new java.awt.Dimension(300, 40));
        txtSDT.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel1.add(txtSDT, gridBagConstraints);

        btnKiemTra.setBackground(new java.awt.Color(204, 255, 255));
        btnKiemTra.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnKiemTra.setText("Kiểm tra");
        btnKiemTra.setPreferredSize(new java.awt.Dimension(120, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        jPanel1.add(btnKiemTra, gridBagConstraints);

        lblTenKH.setBackground(new java.awt.Color(255, 255, 255));
        lblTenKH.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        lblTenKH.setText("Tên khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel1.add(lblTenKH, gridBagConstraints);

        txtTenKhach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenKhach.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTenKhach.setEnabled(false);
        txtTenKhach.setMinimumSize(new java.awt.Dimension(150, 40));
        txtTenKhach.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel1.add(txtTenKhach, gridBagConstraints);

        btnQuayLai.setBackground(new java.awt.Color(153, 204, 255));
        btnQuayLai.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.setPreferredSize(new java.awt.Dimension(120, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(btnQuayLai, gridBagConstraints);

        btnDatPhong.setBackground(new java.awt.Color(204, 255, 204));
        btnDatPhong.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnDatPhong.setText("Đặt phòng");
        btnDatPhong.setPreferredSize(new java.awt.Dimension(120, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel1.add(btnDatPhong, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoaiPhongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoaiPhongActionPerformed

    private void txtSoNguoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoNguoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoNguoiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatPhong;
    private javax.swing.JButton btnKiemTra;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGiaTien;
    private javax.swing.JLabel lblLoaiPhong;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSoNguoi;
    private javax.swing.JLabel lblSoPhong;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JPanel panelC;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtLoaiPhong;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoNguoi;
    private javax.swing.JTextField txtSoPhong;
    private javax.swing.JTextField txtTenKhach;
    // End of variables declaration//GEN-END:variables
}
