/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.Timer;

/**
 *
 * @author PC BAO THONG
 */
public class GD_DatPhong extends javax.swing.JPanel {

    /**
     * Creates new form GD_DatPhong
     */
    public GD_DatPhong() {
        initComponents();
        hienThiNgay();
    }
    private void hienThiNgay() {
        // Tạo JLabel để hiển thị ngày và giờ
        jPanel12.setLayout(new GridBagLayout());
        JLabel dateLabel = new JLabel();
        JLabel timeLabel = new JLabel();

        jPanel12.add(dateLabel);
        jPanel12.add(timeLabel);
        // Định dạng cho ngày và giờ
        SimpleDateFormat dateFormatter = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat timeFormatter = new SimpleDateFormat("hh:mm a");

        // Tạo một GridBagConstraints để canh chỉnh phần tử vào giữa
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.insets = new Insets(5, 5, 5, 5); // Khoảng cách từ các lề
        constraints.anchor = GridBagConstraints.CENTER; // Canh giữa

        constraints.gridy = 0; // Hàng 0 cho ngày
        dateLabel.setFont(new Font("Cambria", Font.PLAIN, 16));
        jPanel12.add(dateLabel, constraints);

        constraints.gridy = 1; // Hàng 1 cho giờ
        timeLabel.setFont(new Font("Cambria", Font.PLAIN, 16));
        jPanel12.add(timeLabel, constraints);

        Timer timer = new Timer(1000, e -> {
            Calendar calendar = Calendar.getInstance();
            Date now = calendar.getTime();

            String formattedDate = dateFormatter.format(now);
            String formattedTime = timeFormatter.format(now);

            dateLabel.setText("Date: " + formattedDate);
            timeLabel.setText("Time: " + formattedTime);
        });
        timer.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        GD_Phong = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        panelPhong = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        GD_Phong.setBackground(new java.awt.Color(121, 188, 215));
        GD_Phong.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        GD_Phong.setMinimumSize(new java.awt.Dimension(1200, 520));
        GD_Phong.setPreferredSize(new java.awt.Dimension(1200, 520));
        GD_Phong.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jPanel13.setPreferredSize(new java.awt.Dimension(1200, 80));
        java.awt.GridBagLayout jPanel13Layout = new java.awt.GridBagLayout();
        jPanel13Layout.columnWidths = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0};
        jPanel13Layout.rowHeights = new int[] {0, 5, 0};
        jPanel13.setLayout(jPanel13Layout);

        jLabel16.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel16.setText("Trạng thái phòng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel13.add(jLabel16, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel17.setText("Loại phòng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel13.add(jLabel17, gridBagConstraints);

        jLabel18.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel18.setText("Mã phòng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel13.add(jLabel18, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel19.setText("Số người");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel13.add(jLabel19, gridBagConstraints);

        jComboBox1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Đang sử dụng", "Đã đặt trước", "Trống" }));
        jComboBox1.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel13.add(jComboBox1, gridBagConstraints);

        jComboBox2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Phòng thường", "Phòng VIP" }));
        jComboBox2.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel13.add(jComboBox2, gridBagConstraints);

        jComboBox3.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "5", "10" }));
        jComboBox3.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        jPanel13.add(jComboBox3, gridBagConstraints);

        jTextField5.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jTextField5.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel13.add(jTextField5, gridBagConstraints);

        jButton12.setBackground(new java.awt.Color(121, 188, 215));
        jButton12.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("Tìm");
        jButton12.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        jPanel13.add(jButton12, gridBagConstraints);

        jButton13.setBackground(new java.awt.Color(0, 255, 153));
        jButton13.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("Làm mới");
        jButton13.setPreferredSize(new java.awt.Dimension(120, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        jPanel13.add(jButton13, gridBagConstraints);

        GD_Phong.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        jPanel9.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jPanel9.setMinimumSize(new java.awt.Dimension(1200, 80));
        jPanel9.setPreferredSize(new java.awt.Dimension(1200, 80));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jPanel10.setPreferredSize(new java.awt.Dimension(1200, 50));
        java.awt.GridBagLayout jPanel10Layout = new java.awt.GridBagLayout();
        jPanel10Layout.columnWidths = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0};
        jPanel10Layout.rowHeights = new int[] {0};
        jPanel10.setLayout(jPanel10Layout);

        jLabel12.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/phongV.png"))); // NOI18N
        jLabel12.setText("Phòng VIP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        jPanel10.add(jLabel12, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/phongT.png"))); // NOI18N
        jLabel6.setText("Phòng thường");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 0;
        jPanel10.add(jLabel6, gridBagConstraints);

        jLabel13.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pDSD.png"))); // NOI18N
        jLabel13.setText("Đang sử dụng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel10.add(jLabel13, gridBagConstraints);

        jLabel14.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pDDT.png"))); // NOI18N
        jLabel14.setText("Đã đặt trước");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel10.add(jLabel14, gridBagConstraints);

        jLabel15.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pT.png"))); // NOI18N
        jLabel15.setText("Phòng trống");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        jPanel10.add(jLabel15, gridBagConstraints);

        jPanel9.add(jPanel10, java.awt.BorderLayout.CENTER);

        GD_Phong.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setMinimumSize(new java.awt.Dimension(970, 370));
        jPanel14.setLayout(new java.awt.BorderLayout());

        panelPhong.setLayout(new java.awt.GridBagLayout());
        jPanel14.add(panelPhong, java.awt.BorderLayout.CENTER);

        GD_Phong.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(new java.awt.Color(121, 188, 215));
        jPanel8.setMaximumSize(new java.awt.Dimension(300, 2147483647));
        jPanel8.setMinimumSize(new java.awt.Dimension(220, 320));
        jPanel8.setPreferredSize(new java.awt.Dimension(220, 320));
        jPanel8.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel11.setMinimumSize(new java.awt.Dimension(220, 200));
        java.awt.GridBagLayout jPanel11Layout = new java.awt.GridBagLayout();
        jPanel11Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel11Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel11.setLayout(jPanel11Layout);

        jButton5.setBackground(new java.awt.Color(64, 71, 214));
        jButton5.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Xem chi tiết (F1)");
        jButton5.setToolTipText("");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMaximumSize(new java.awt.Dimension(200, 30));
        jButton5.setMinimumSize(new java.awt.Dimension(200, 30));
        jButton5.setPreferredSize(new java.awt.Dimension(200, 30));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        jPanel11.add(jButton5, gridBagConstraints);

        jButton6.setBackground(new java.awt.Color(64, 71, 214));
        jButton6.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Đặt trước phòng (F2)");
        jButton6.setMaximumSize(new java.awt.Dimension(200, 30));
        jButton6.setMinimumSize(new java.awt.Dimension(200, 30));
        jButton6.setPreferredSize(new java.awt.Dimension(200, 30));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        jPanel11.add(jButton6, gridBagConstraints);

        jButton7.setBackground(new java.awt.Color(64, 71, 214));
        jButton7.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Hủy đặt phòng (F3)");
        jButton7.setMaximumSize(new java.awt.Dimension(200, 30));
        jButton7.setMinimumSize(new java.awt.Dimension(200, 30));
        jButton7.setPreferredSize(new java.awt.Dimension(200, 30));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        jPanel11.add(jButton7, gridBagConstraints);

        jButton8.setBackground(new java.awt.Color(64, 71, 214));
        jButton8.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Nhận phòng (F4)");
        jButton8.setMaximumSize(new java.awt.Dimension(200, 30));
        jButton8.setMinimumSize(new java.awt.Dimension(200, 30));
        jButton8.setPreferredSize(new java.awt.Dimension(200, 30));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        jPanel11.add(jButton8, gridBagConstraints);

        jButton9.setBackground(new java.awt.Color(64, 71, 214));
        jButton9.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Trả phòng (F5)");
        jButton9.setMaximumSize(new java.awt.Dimension(200, 30));
        jButton9.setMinimumSize(new java.awt.Dimension(200, 30));
        jButton9.setPreferredSize(new java.awt.Dimension(200, 30));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        jPanel11.add(jButton9, gridBagConstraints);

        jButton10.setBackground(new java.awt.Color(64, 71, 214));
        jButton10.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Thêm dịch vụ (F6)");
        jButton10.setMaximumSize(new java.awt.Dimension(200, 30));
        jButton10.setMinimumSize(new java.awt.Dimension(200, 30));
        jButton10.setPreferredSize(new java.awt.Dimension(200, 30));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        jPanel11.add(jButton10, gridBagConstraints);

        jButton11.setBackground(new java.awt.Color(64, 71, 214));
        jButton11.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("Cập nhật dịch vụ (F7)");
        jButton11.setMaximumSize(new java.awt.Dimension(200, 30));
        jButton11.setMinimumSize(new java.awt.Dimension(200, 30));
        jButton11.setPreferredSize(new java.awt.Dimension(200, 30));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        jPanel11.add(jButton11, gridBagConstraints);

        jPanel8.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jPanel12.setMinimumSize(new java.awt.Dimension(220, 100));
        jPanel12.setPreferredSize(new java.awt.Dimension(220, 50));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel12, java.awt.BorderLayout.PAGE_START);

        GD_Phong.add(jPanel8, java.awt.BorderLayout.WEST);

        add(GD_Phong, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GD_Phong;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPanel panelPhong;
    // End of variables declaration//GEN-END:variables
}
