/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Font;
import javax.swing.DefaultCellEditor;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author PC BAO THONG
 */
public class GD_DSPhong extends javax.swing.JPanel {

    /**
     * Creates new form GD_Phong
     */
    public GD_DSPhong() {
        initComponents();
        tableDanhSachPhong();
    }
    private void tableDanhSachPhong() {
        PromptSupport.setPrompt("Nhập mã phòng", txtTP);
        tableDSPhong.getTableHeader().setFont(new Font("Cambria", Font.PLAIN, 16));
        tableDSPhong.getTableHeader().setOpaque(false);
        tableDSPhong.getTableHeader().setBackground(new Color(32, 136, 203));
        tableDSPhong.getTableHeader().setForeground(new Color(255, 255, 255));
        tableDSPhong.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(comboSucChua));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btngTrangThai = new javax.swing.ButtonGroup();
        GD_DSPhong = new javax.swing.JPanel();
        panelNorth2 = new javax.swing.JPanel();
        lblMaDV1 = new javax.swing.JLabel();
        txtMaDV1 = new javax.swing.JTextField();
        lblDonGia1 = new javax.swing.JLabel();
        txtDonGia1 = new javax.swing.JTextField();
        lblTenDV1 = new javax.swing.JLabel();
        txtTenDV1 = new javax.swing.JTextField();
        lblHsd1 = new javax.swing.JLabel();
        lblXuatXu1 = new javax.swing.JLabel();
        comboXuatXu1 = new javax.swing.JComboBox<>();
        lblDonViBan1 = new javax.swing.JLabel();
        comboSucChua = new javax.swing.JComboBox<>();
        lblTinhTrang1 = new javax.swing.JLabel();
        radioDangBan1 = new javax.swing.JRadioButton();
        radioNgungBan1 = new javax.swing.JRadioButton();
        btnCapNhatDV1 = new javax.swing.JButton();
        btnLamMoi3 = new javax.swing.JButton();
        btnXoa3 = new javax.swing.JButton();
        btnTim2 = new javax.swing.JButton();
        txtTP = new javax.swing.JTextField();
        txtTenDV2 = new javax.swing.JTextField();
        panelCenter1 = new javax.swing.JPanel();
        scrollPane2 = new javax.swing.JScrollPane();
        tableDSPhong = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        GD_DSPhong.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        GD_DSPhong.setMinimumSize(new java.awt.Dimension(1200, 520));
        GD_DSPhong.setPreferredSize(new java.awt.Dimension(1200, 520));
        GD_DSPhong.setLayout(new java.awt.BorderLayout());

        panelNorth2.setBackground(new java.awt.Color(255, 255, 255));
        panelNorth2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N
        panelNorth2.setMinimumSize(new java.awt.Dimension(1200, 300));
        panelNorth2.setPreferredSize(new java.awt.Dimension(1200, 300));
        java.awt.GridBagLayout panelNorth2Layout = new java.awt.GridBagLayout();
        panelNorth2Layout.columnWidths = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0};
        panelNorth2Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        panelNorth2.setLayout(panelNorth2Layout);

        lblMaDV1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblMaDV1.setText("Mã phòng");
        lblMaDV1.setMaximumSize(new java.awt.Dimension(110, 40));
        lblMaDV1.setMinimumSize(new java.awt.Dimension(110, 40));
        lblMaDV1.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth2.add(lblMaDV1, gridBagConstraints);

        txtMaDV1.setBackground(new java.awt.Color(242, 242, 242));
        txtMaDV1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtMaDV1.setText("DVB001");
        txtMaDV1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMaDV1.setEnabled(false);
        txtMaDV1.setMaximumSize(new java.awt.Dimension(250, 30));
        txtMaDV1.setMinimumSize(new java.awt.Dimension(250, 30));
        txtMaDV1.setPreferredSize(new java.awt.Dimension(200, 30));
        txtMaDV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDV1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        panelNorth2.add(txtMaDV1, gridBagConstraints);

        lblDonGia1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblDonGia1.setText("Đơn giá");
        lblDonGia1.setMaximumSize(new java.awt.Dimension(155, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth2.add(lblDonGia1, gridBagConstraints);

        txtDonGia1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtDonGia1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDonGia1.setMaximumSize(new java.awt.Dimension(250, 30));
        txtDonGia1.setMinimumSize(new java.awt.Dimension(250, 30));
        txtDonGia1.setPreferredSize(new java.awt.Dimension(200, 30));
        txtDonGia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGia1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        panelNorth2.add(txtDonGia1, gridBagConstraints);

        lblTenDV1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblTenDV1.setText("Mã loại phòng");
        lblTenDV1.setMaximumSize(new java.awt.Dimension(110, 40));
        lblTenDV1.setMinimumSize(new java.awt.Dimension(110, 40));
        lblTenDV1.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth2.add(lblTenDV1, gridBagConstraints);

        txtTenDV1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTenDV1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTenDV1.setMaximumSize(new java.awt.Dimension(250, 30));
        txtTenDV1.setMinimumSize(new java.awt.Dimension(250, 30));
        txtTenDV1.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        panelNorth2.add(txtTenDV1, gridBagConstraints);

        lblHsd1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblHsd1.setText("Tên loại phòng");
        lblHsd1.setMaximumSize(new java.awt.Dimension(110, 40));
        lblHsd1.setMinimumSize(new java.awt.Dimension(110, 40));
        lblHsd1.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth2.add(lblHsd1, gridBagConstraints);

        lblXuatXu1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblXuatXu1.setText("Tình trạng");
        lblXuatXu1.setMaximumSize(new java.awt.Dimension(110, 40));
        lblXuatXu1.setMinimumSize(new java.awt.Dimension(110, 40));
        lblXuatXu1.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth2.add(lblXuatXu1, gridBagConstraints);

        comboXuatXu1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        comboXuatXu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống", "Đã được đặt", "Đang sử dụng" }));
        comboXuatXu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboXuatXu1.setMaximumSize(new java.awt.Dimension(250, 30));
        comboXuatXu1.setMinimumSize(new java.awt.Dimension(250, 30));
        comboXuatXu1.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        panelNorth2.add(comboXuatXu1, gridBagConstraints);

        lblDonViBan1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblDonViBan1.setText("Sức chứa");
        lblDonViBan1.setMaximumSize(new java.awt.Dimension(110, 40));
        lblDonViBan1.setMinimumSize(new java.awt.Dimension(110, 40));
        lblDonViBan1.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth2.add(lblDonViBan1, gridBagConstraints);

        comboSucChua.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        comboSucChua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "15", "20" }));
        comboSucChua.setMaximumSize(new java.awt.Dimension(250, 30));
        comboSucChua.setMinimumSize(new java.awt.Dimension(250, 30));
        comboSucChua.setPreferredSize(new java.awt.Dimension(200, 30));
        comboSucChua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSucChuaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        panelNorth2.add(comboSucChua, gridBagConstraints);

        lblTinhTrang1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblTinhTrang1.setText("Trạng thái");
        lblTinhTrang1.setMaximumSize(new java.awt.Dimension(110, 40));
        lblTinhTrang1.setMinimumSize(new java.awt.Dimension(110, 40));
        lblTinhTrang1.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth2.add(lblTinhTrang1, gridBagConstraints);

        radioDangBan1.setBackground(new java.awt.Color(255, 255, 255));
        btngTrangThai.add(radioDangBan1);
        radioDangBan1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        radioDangBan1.setText("Bảo trì");
        radioDangBan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDangBan1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth2.add(radioDangBan1, gridBagConstraints);

        radioNgungBan1.setBackground(new java.awt.Color(255, 255, 255));
        btngTrangThai.add(radioNgungBan1);
        radioNgungBan1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        radioNgungBan1.setText("Sẵn sàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        panelNorth2.add(radioNgungBan1, gridBagConstraints);

        btnCapNhatDV1.setBackground(new java.awt.Color(102, 255, 51));
        btnCapNhatDV1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnCapNhatDV1.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhatDV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/system-update.png"))); // NOI18N
        btnCapNhatDV1.setText("Cập nhật thông tin");
        btnCapNhatDV1.setMaximumSize(new java.awt.Dimension(210, 40));
        btnCapNhatDV1.setMinimumSize(new java.awt.Dimension(210, 30));
        btnCapNhatDV1.setPreferredSize(new java.awt.Dimension(210, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth2.add(btnCapNhatDV1, gridBagConstraints);

        btnLamMoi3.setBackground(new java.awt.Color(0, 255, 153));
        btnLamMoi3.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnLamMoi3.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        btnLamMoi3.setText("Làm mới");
        btnLamMoi3.setMaximumSize(new java.awt.Dimension(135, 40));
        btnLamMoi3.setMinimumSize(new java.awt.Dimension(135, 30));
        btnLamMoi3.setPreferredSize(new java.awt.Dimension(130, 30));
        btnLamMoi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoi3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 16;
        panelNorth2.add(btnLamMoi3, gridBagConstraints);

        btnXoa3.setBackground(new java.awt.Color(204, 204, 204));
        btnXoa3.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnXoa3.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eraser.png"))); // NOI18N
        btnXoa3.setText("Xóa trắng");
        btnXoa3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoa3.setMaximumSize(new java.awt.Dimension(135, 40));
        btnXoa3.setMinimumSize(new java.awt.Dimension(135, 30));
        btnXoa3.setPreferredSize(new java.awt.Dimension(120, 30));
        btnXoa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        panelNorth2.add(btnXoa3, gridBagConstraints);

        btnTim2.setBackground(new java.awt.Color(121, 188, 215));
        btnTim2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnTim2.setForeground(new java.awt.Color(255, 255, 255));
        btnTim2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search-user.png"))); // NOI18N
        btnTim2.setText("Tìm");
        btnTim2.setMaximumSize(new java.awt.Dimension(90, 30));
        btnTim2.setMinimumSize(new java.awt.Dimension(90, 30));
        btnTim2.setPreferredSize(new java.awt.Dimension(135, 30));
        btnTim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth2.add(btnTim2, gridBagConstraints);

        txtTP.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTP.setMaximumSize(new java.awt.Dimension(250, 30));
        txtTP.setMinimumSize(new java.awt.Dimension(250, 30));
        txtTP.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        panelNorth2.add(txtTP, gridBagConstraints);

        txtTenDV2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTenDV2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTenDV2.setMaximumSize(new java.awt.Dimension(250, 30));
        txtTenDV2.setMinimumSize(new java.awt.Dimension(250, 30));
        txtTenDV2.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        panelNorth2.add(txtTenDV2, gridBagConstraints);

        GD_DSPhong.add(panelNorth2, java.awt.BorderLayout.PAGE_START);

        panelCenter1.setBackground(new java.awt.Color(255, 255, 255));
        panelCenter1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        panelCenter1.setLayout(new java.awt.BorderLayout());

        scrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N
        scrollPane2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        scrollPane2.setMinimumSize(new java.awt.Dimension(1200, 160));
        scrollPane2.setPreferredSize(new java.awt.Dimension(1200, 900));

        tableDSPhong.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        tableDSPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phòng", "Mã loại phòng", "Tên loại phòng", "Đơn giá", "Sức chứa", "Tình trạng", "Trạng thái"
            }
        ));
        tableDSPhong.setMinimumSize(new java.awt.Dimension(1200, 300));
        tableDSPhong.setPreferredSize(new java.awt.Dimension(1200, 900));
        tableDSPhong.setRowHeight(25);
        tableDSPhong.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tableDSPhong.setShowHorizontalLines(true);
        tableDSPhong.getTableHeader().setReorderingAllowed(false);
        scrollPane2.setViewportView(tableDSPhong);

        panelCenter1.add(scrollPane2, java.awt.BorderLayout.CENTER);

        GD_DSPhong.add(panelCenter1, java.awt.BorderLayout.CENTER);

        add(GD_DSPhong, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaDV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDV1ActionPerformed

    private void txtDonGia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGia1ActionPerformed

    private void comboSucChuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSucChuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSucChuaActionPerformed

    private void radioDangBan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDangBan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDangBan1ActionPerformed

    private void btnLamMoi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoi3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoi3ActionPerformed

    private void btnXoa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoa3ActionPerformed

    private void btnTim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTim2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTim2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GD_DSPhong;
    private javax.swing.JButton btnCapNhatDV1;
    private javax.swing.JButton btnLamMoi3;
    private javax.swing.JButton btnTim2;
    private javax.swing.JButton btnXoa3;
    private javax.swing.ButtonGroup btngTrangThai;
    private javax.swing.JComboBox<String> comboSucChua;
    private javax.swing.JComboBox<String> comboXuatXu1;
    private javax.swing.JLabel lblDonGia1;
    private javax.swing.JLabel lblDonViBan1;
    private javax.swing.JLabel lblHsd1;
    private javax.swing.JLabel lblMaDV1;
    private javax.swing.JLabel lblTenDV1;
    private javax.swing.JLabel lblTinhTrang1;
    private javax.swing.JLabel lblXuatXu1;
    private javax.swing.JPanel panelCenter1;
    private javax.swing.JPanel panelNorth2;
    private javax.swing.JRadioButton radioDangBan1;
    private javax.swing.JRadioButton radioNgungBan1;
    private javax.swing.JScrollPane scrollPane2;
    private javax.swing.JTable tableDSPhong;
    private javax.swing.JTextField txtDonGia1;
    private javax.swing.JTextField txtMaDV1;
    private javax.swing.JTextField txtTP;
    private javax.swing.JTextField txtTenDV1;
    private javax.swing.JTextField txtTenDV2;
    // End of variables declaration//GEN-END:variables
}
