/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.toedter.calendar.JDateChooserCellEditor;
import com.toedter.components.JSpinField;
import java.awt.Color;
import java.awt.Font;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.TableCellEditor;
import org.jdesktop.swingx.JXTable;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author PC BAO THONG
 */
public class GD_DichVu extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachNhanVien
     */
    public GD_DichVu() {
        initComponents();
        setTitle("Quản lý nhân viên");
        //setResizable(false);
        setLocationRelativeTo(null);
        PromptSupport.setPrompt("Nhập mã dịch vụ", txtTim);
        table();
    }

    private void table() {
        tableDichVu.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 18));
        tableDichVu.getTableHeader().setOpaque(false);
        tableDichVu.getTableHeader().setBackground(new Color(32, 136, 203));
        tableDichVu.getTableHeader().setForeground(new Color(255, 255, 255));
        //đơn vị bán
        String[] donVi = {"Lon", "Cái", "Đĩa", "Hộp"};
        JComboBox comboBoxDV = new JComboBox(donVi);
        comboBoxDV.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        comboBoxDV.setBackground(new Color(255, 255, 255));
        tableDichVu.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(comboBoxDV));
        //xuất xứ
        String[] xuatXu = {"Việt Nam", "Thái Lan", "Trung Quốc", "Hoa Kỳ", "Đức"};
        JComboBox comboBoxXX = new JComboBox(xuatXu);
        comboBoxXX.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        comboBoxXX.setBackground(new Color(255, 255, 255));
        tableDichVu.getColumnModel().getColumn(6).setCellEditor(new DefaultCellEditor(comboBoxXX));
        //tình trạng
        String[] tinhTrang = {"Đang cung cấp", "Ngừng cung cấp"};
        JComboBox comboBoxTT = new JComboBox(tinhTrang);
        comboBoxTT.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        comboBoxTT.setBackground(new Color(255, 255, 255));
        tableDichVu.getColumnModel().getColumn(7).setCellEditor(new DefaultCellEditor(comboBoxTT));
        //HSD
        tableDichVu.getColumnModel().getColumn(5).setCellEditor(new JDateChooserCellEditor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGroupTinhTrang = new javax.swing.ButtonGroup();
        panelHeader = new javax.swing.JPanel();
        panelL = new javax.swing.JPanel();
        panelC = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();
        panelR = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        panelSouth = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        tableDichVu = new javax.swing.JTable();
        panelCenter = new javax.swing.JPanel();
        lblMaDV = new javax.swing.JLabel();
        txtMaDV = new javax.swing.JTextField();
        lblDonGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        lblTenDV = new javax.swing.JLabel();
        txtTenDV = new javax.swing.JTextField();
        lblHsd = new javax.swing.JLabel();
        hsd = new com.toedter.calendar.JDateChooser();
        lblXuatXu = new javax.swing.JLabel();
        comboXuatXu = new javax.swing.JComboBox<>();
        lblDonViBan = new javax.swing.JLabel();
        comboDVB = new javax.swing.JComboBox<>();
        lblSoLuong = new javax.swing.JLabel();
        spinSoLuong = new com.toedter.components.JSpinField();
        lblTinhTrang = new javax.swing.JLabel();
        radioDangBan = new javax.swing.JRadioButton();
        radioNgungBan = new javax.swing.JRadioButton();
        btnThemDV = new javax.swing.JButton();
        btnCapNhatDV = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setPreferredSize(new java.awt.Dimension(1200, 40));
        panelHeader.setLayout(new java.awt.GridLayout(1, 0));

        panelL.setBackground(new java.awt.Color(121, 188, 215));

        javax.swing.GroupLayout panelLLayout = new javax.swing.GroupLayout(panelL);
        panelL.setLayout(panelLLayout);
        panelLLayout.setHorizontalGroup(
            panelLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLLayout.setVerticalGroup(
            panelLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelHeader.add(panelL);

        panelC.setBackground(new java.awt.Color(121, 188, 215));
        panelC.setLayout(new java.awt.GridBagLayout());

        lblTittle.setBackground(new java.awt.Color(255, 255, 255));
        lblTittle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(33, 36, 71));
        lblTittle.setText("QUẢN LÝ DỊCH VỤ");
        lblTittle.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panelC.add(lblTittle, new java.awt.GridBagConstraints());

        panelHeader.add(panelC);

        panelR.setBackground(new java.awt.Color(121, 188, 215));
        panelR.setPreferredSize(new java.awt.Dimension(300, 40));
        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {0, 10, 0};
        jPanel4Layout.rowHeights = new int[] {0};
        panelR.setLayout(jPanel4Layout);

        lblUser.setBackground(new java.awt.Color(255, 255, 255));
        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N
        lblUser.setText("Quản lý - Đặng Bảo Thông");
        lblUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelR.add(lblUser, gridBagConstraints);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.setContentAreaFilled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        panelR.add(btnLogout, gridBagConstraints);

        panelHeader.add(panelR);

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelSouth.setBackground(new java.awt.Color(255, 255, 255));
        panelSouth.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelSouth.setLayout(new java.awt.BorderLayout());

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        tableDichVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Đơn vị bán", "Số lượng tồn", "Đơn giá", "Hạn sử dụng", "Xuất xứ", "Tình trạng"
            }
        ));
        tableDichVu.setRowHeight(25);
        tableDichVu.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tableDichVu.setShowHorizontalLines(true);
        tableDichVu.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(tableDichVu);

        panelSouth.add(scrollPane, java.awt.BorderLayout.CENTER);
        scrollPane.getAccessibleContext().setAccessibleName("");

        getContentPane().add(panelSouth, java.awt.BorderLayout.SOUTH);

        panelCenter.setBackground(new java.awt.Color(255, 255, 255));
        panelCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0};
        jPanel1Layout.rowHeights = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0};
        panelCenter.setLayout(jPanel1Layout);

        lblMaDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaDV.setText("Mã dịch vụ");
        lblMaDV.setMaximumSize(new java.awt.Dimension(110, 40));
        lblMaDV.setMinimumSize(new java.awt.Dimension(110, 40));
        lblMaDV.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblMaDV, gridBagConstraints);

        txtMaDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMaDV.setEnabled(false);
        txtMaDV.setMaximumSize(new java.awt.Dimension(250, 40));
        txtMaDV.setMinimumSize(new java.awt.Dimension(250, 40));
        txtMaDV.setPreferredSize(new java.awt.Dimension(250, 40));
        txtMaDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        panelCenter.add(txtMaDV, gridBagConstraints);

        lblDonGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDonGia.setText("Đơn giá");
        lblDonGia.setMaximumSize(new java.awt.Dimension(155, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblDonGia, gridBagConstraints);

        txtDonGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDonGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDonGia.setMaximumSize(new java.awt.Dimension(250, 40));
        txtDonGia.setMinimumSize(new java.awt.Dimension(250, 40));
        txtDonGia.setPreferredSize(new java.awt.Dimension(250, 40));
        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        panelCenter.add(txtDonGia, gridBagConstraints);

        lblTenDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTenDV.setText("Tên dịch vụ");
        lblTenDV.setMaximumSize(new java.awt.Dimension(110, 40));
        lblTenDV.setMinimumSize(new java.awt.Dimension(110, 40));
        lblTenDV.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblTenDV, gridBagConstraints);

        txtTenDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTenDV.setMaximumSize(new java.awt.Dimension(250, 40));
        txtTenDV.setMinimumSize(new java.awt.Dimension(250, 40));
        txtTenDV.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        panelCenter.add(txtTenDV, gridBagConstraints);

        lblHsd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHsd.setText("Hạn sử dụng");
        lblHsd.setMaximumSize(new java.awt.Dimension(110, 40));
        lblHsd.setMinimumSize(new java.awt.Dimension(110, 40));
        lblHsd.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblHsd, gridBagConstraints);

        hsd.setBackground(new java.awt.Color(255, 255, 255));
        hsd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hsd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hsd.setMaximumSize(new java.awt.Dimension(250, 40));
        hsd.setMinimumSize(new java.awt.Dimension(250, 40));
        hsd.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        panelCenter.add(hsd, gridBagConstraints);

        lblXuatXu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblXuatXu.setText("Xuất xứ");
        lblXuatXu.setMaximumSize(new java.awt.Dimension(110, 40));
        lblXuatXu.setMinimumSize(new java.awt.Dimension(110, 40));
        lblXuatXu.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblXuatXu, gridBagConstraints);

        comboXuatXu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboXuatXu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Việt Nam", "Thái Lan", "Trung Quốc", "Hoa Kỳ", "Đức" }));
        comboXuatXu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboXuatXu.setMaximumSize(new java.awt.Dimension(250, 40));
        comboXuatXu.setMinimumSize(new java.awt.Dimension(250, 40));
        comboXuatXu.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        panelCenter.add(comboXuatXu, gridBagConstraints);

        lblDonViBan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDonViBan.setText("Đơn vị bán");
        lblDonViBan.setMaximumSize(new java.awt.Dimension(110, 40));
        lblDonViBan.setMinimumSize(new java.awt.Dimension(110, 40));
        lblDonViBan.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblDonViBan, gridBagConstraints);

        comboDVB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboDVB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lon", "Cái", "Đĩa", "Hộp" }));
        comboDVB.setMaximumSize(new java.awt.Dimension(250, 40));
        comboDVB.setMinimumSize(new java.awt.Dimension(250, 40));
        comboDVB.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        panelCenter.add(comboDVB, gridBagConstraints);

        lblSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSoLuong.setText("Số lượng tồn");
        lblSoLuong.setMaximumSize(new java.awt.Dimension(110, 40));
        lblSoLuong.setMinimumSize(new java.awt.Dimension(110, 40));
        lblSoLuong.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblSoLuong, gridBagConstraints);

        spinSoLuong.setMaximumSize(new java.awt.Dimension(100, 40));
        spinSoLuong.setMinimum(0);
        spinSoLuong.setMinimumSize(new java.awt.Dimension(100, 40));
        spinSoLuong.setPreferredSize(new java.awt.Dimension(100, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(spinSoLuong, gridBagConstraints);

        lblTinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTinhTrang.setText("Tình trạng");
        lblTinhTrang.setMaximumSize(new java.awt.Dimension(110, 40));
        lblTinhTrang.setMinimumSize(new java.awt.Dimension(110, 40));
        lblTinhTrang.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblTinhTrang, gridBagConstraints);

        radioDangBan.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupTinhTrang.add(radioDangBan);
        radioDangBan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radioDangBan.setText("Đang bán");
        radioDangBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDangBanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(radioDangBan, gridBagConstraints);

        radioNgungBan.setBackground(new java.awt.Color(255, 255, 255));
        btnGroupTinhTrang.add(radioNgungBan);
        radioNgungBan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radioNgungBan.setText("Ngừng bán");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        panelCenter.add(radioNgungBan, gridBagConstraints);

        btnThemDV.setBackground(new java.awt.Color(51, 102, 255));
        btnThemDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThemDV.setForeground(new java.awt.Color(255, 255, 255));
        btnThemDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add-user.png"))); // NOI18N
        btnThemDV.setText("Thêm dịch vụ");
        btnThemDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(btnThemDV, gridBagConstraints);

        btnCapNhatDV.setBackground(new java.awt.Color(102, 255, 51));
        btnCapNhatDV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCapNhatDV.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhatDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/system-update.png"))); // NOI18N
        btnCapNhatDV.setText("Cập nhật thông tin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        panelCenter.add(btnCapNhatDV, gridBagConstraints);

        btnLamMoi.setBackground(new java.awt.Color(0, 255, 153));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(btnLamMoi, gridBagConstraints);

        btnXoa.setBackground(new java.awt.Color(204, 204, 204));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eraser.png"))); // NOI18N
        btnXoa.setText("Xóa trắng");
        btnXoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoa.setMaximumSize(new java.awt.Dimension(127, 32));
        btnXoa.setMinimumSize(new java.awt.Dimension(127, 32));
        btnXoa.setPreferredSize(new java.awt.Dimension(127, 32));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        panelCenter.add(btnXoa, gridBagConstraints);

        btnTim.setBackground(new java.awt.Color(121, 188, 215));
        btnTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search-user.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        panelCenter.add(btnTim, gridBagConstraints);

        txtTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTim.setMaximumSize(new java.awt.Dimension(250, 40));
        txtTim.setMinimumSize(new java.awt.Dimension(250, 40));
        txtTim.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        panelCenter.add(txtTim, gridBagConstraints);

        getContentPane().add(panelCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDVActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void btnThemDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemDVActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void radioDangBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDangBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDangBanActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_DichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_DichVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatDV;
    private javax.swing.ButtonGroup btnGroupTinhTrang;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnThemDV;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> comboDVB;
    private javax.swing.JComboBox<String> comboXuatXu;
    private com.toedter.calendar.JDateChooser hsd;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblDonViBan;
    private javax.swing.JLabel lblHsd;
    private javax.swing.JLabel lblMaDV;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenDV;
    private javax.swing.JLabel lblTinhTrang;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblXuatXu;
    private javax.swing.JPanel panelC;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelL;
    private javax.swing.JPanel panelR;
    private javax.swing.JPanel panelSouth;
    private javax.swing.JRadioButton radioDangBan;
    private javax.swing.JRadioButton radioNgungBan;
    private javax.swing.JScrollPane scrollPane;
    private com.toedter.components.JSpinField spinSoLuong;
    private javax.swing.JTable tableDichVu;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextField txtTenDV;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
