/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.toedter.calendar.JDateChooserCellEditor;
import connectDB.ConnectDB;
import dao.HoaDon_DAO;
import entity.HoaDon;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author PC BAO THONG
 */
public class GD_HD extends javax.swing.JPanel {
    //DAO
    private HoaDon_DAO hd_dao;

    //HoaDon
    private DefaultTableModel modelHD;

    /**
     * Creates new form GD_HD
     */
    public GD_HD() {
        try {
            ConnectDB.getInstance().connect();
            System.out.println("Ket noi Database thanh cong");
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        hd_dao = new HoaDon_DAO();
        initComponents();
        tableHoaDon();
    }

    private void tableHoaDon() {
        PromptSupport.setPrompt("Nhập số điện thoại khách", txtHD);
        tableHD.getTableHeader().setFont(new Font("Cambria", Font.PLAIN, 16));
        tableHD.getTableHeader().setOpaque(false);
        tableHD.getTableHeader().setBackground(new Color(32, 136, 203));
        tableHD.getTableHeader().setForeground(new Color(255, 255, 255));
        tableHD.getColumnModel().getColumn(1).setCellEditor(new JDateChooserCellEditor());
        modelHD = (DefaultTableModel) tableHD.getModel();
        napDuLieuHD();
    }
    private void napDuLieuHD() {
        ArrayList<HoaDon> dsHD;
        dsHD = hd_dao.getAllHoaDon();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        for (HoaDon hd : dsHD) {
            String ngayLap = formatter.format(hd.getGioKetThuc());
            modelHD.addRow(new Object[]{hd.getMaHD(), ngayLap, hd.getKhachHang().getHoKH() + " " + hd.getKhachHang().getTenKH(),
                hd.getKhachHang().getSdtKH(), hd.getNhanVienLap().getHoNV() + " " + hd.getNhanVienLap().getTenNV(), hd.getTongTien()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        GD_HoaDon = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableHD = new javax.swing.JTable();
        jPanel18 = new javax.swing.JPanel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        txtHD = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jSpinField1 = new com.toedter.components.JSpinField();
        jSpinField2 = new com.toedter.components.JSpinField();

        setLayout(new java.awt.BorderLayout());

        GD_HoaDon.setBackground(new java.awt.Color(255, 255, 255));
        GD_HoaDon.setLayout(new java.awt.BorderLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N
        jPanel17.setMinimumSize(new java.awt.Dimension(1200, 220));
        jPanel17.setPreferredSize(new java.awt.Dimension(1200, 220));
        jPanel17.setLayout(new java.awt.BorderLayout());

        tableHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Ngày lập", "Tên khách hàng", "Số điện thọai", "Nhân viên", "Tổng tiền"
            }
        ));
        tableHD.setRowHeight(25);
        jScrollPane3.setViewportView(tableHD);

        jPanel17.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        GD_HoaDon.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N
        jPanel18.setMinimumSize(new java.awt.Dimension(1200, 300));
        jPanel18.setPreferredSize(new java.awt.Dimension(1200, 300));
        java.awt.GridBagLayout jPanel18Layout = new java.awt.GridBagLayout();
        jPanel18Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel18Layout.rowHeights = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0};
        jPanel18.setLayout(jPanel18Layout);

        jTextField12.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jTextField12.setEnabled(false);
        jTextField12.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextField12.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel18.add(jTextField12, gridBagConstraints);

        jTextField13.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jTextField13.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextField13.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        jPanel18.add(jTextField13, gridBagConstraints);

        jTextField8.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jTextField8.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextField8.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        jPanel18.add(jTextField8, gridBagConstraints);

        jLabel29.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel29.setText("Ngày lập");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel18.add(jLabel29, gridBagConstraints);

        jLabel30.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel30.setText("Mã hóa đơn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel18.add(jLabel30, gridBagConstraints);

        jLabel31.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel31.setText("Tên nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel18.add(jLabel31, gridBagConstraints);

        jLabel32.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel32.setText("Tên khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel18.add(jLabel32, gridBagConstraints);

        jLabel33.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel33.setText("Số điện thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel18.add(jLabel33, gridBagConstraints);

        jDateChooser4.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jDateChooser4.setMinimumSize(new java.awt.Dimension(200, 30));
        jDateChooser4.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel18.add(jDateChooser4, gridBagConstraints);

        jButton17.setBackground(new java.awt.Color(121, 188, 215));
        jButton17.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton17.setForeground(new java.awt.Color(255, 255, 255));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search-doc.png"))); // NOI18N
        jButton17.setText("Tìm");
        jButton17.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton17.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel18.add(jButton17, gridBagConstraints);

        jButton18.setBackground(new java.awt.Color(0, 204, 204));
        jButton18.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paper.png"))); // NOI18N
        jButton18.setText("Xem chi tiết");
        jButton18.setMinimumSize(new java.awt.Dimension(150, 30));
        jButton18.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel18.add(jButton18, gridBagConstraints);

        jButton19.setBackground(new java.awt.Color(0, 255, 213));
        jButton19.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        jButton19.setText("Làm mới");
        jButton19.setMinimumSize(new java.awt.Dimension(15, 30));
        jButton19.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel18.add(jButton19, gridBagConstraints);

        txtHD.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtHD.setMinimumSize(new java.awt.Dimension(200, 30));
        txtHD.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        jPanel18.add(txtHD, gridBagConstraints);

        jTextField15.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jTextField15.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextField15.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 0;
        jPanel18.add(jTextField15, gridBagConstraints);

        jLabel27.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel27.setText("Giờ lập");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel18.add(jLabel27, gridBagConstraints);

        jSpinField1.setMaximum(22);
        jSpinField1.setMinimum(8);
        jSpinField1.setPreferredSize(new java.awt.Dimension(90, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel18.add(jSpinField1, gridBagConstraints);

        jSpinField2.setMaximum(59);
        jSpinField2.setMaximumSize(new java.awt.Dimension(0, 0));
        jSpinField2.setMinimum(0);
        jSpinField2.setPreferredSize(new java.awt.Dimension(90, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel18.add(jSpinField2, gridBagConstraints);

        GD_HoaDon.add(jPanel18, java.awt.BorderLayout.PAGE_START);

        add(GD_HoaDon, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GD_HoaDon;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPane3;
    private com.toedter.components.JSpinField jSpinField1;
    private com.toedter.components.JSpinField jSpinField2;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable tableHD;
    private javax.swing.JTextField txtHD;
    // End of variables declaration//GEN-END:variables
}
