/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.toedter.calendar.JDateChooserCellEditor;
import java.awt.Color;
import java.awt.Font;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author PC BAO THONG
 */
public class GD_KH extends javax.swing.JPanel {

    /**
     * Creates new form GD_KH
     */
    public GD_KH() {
        initComponents();
        tableKhachHang();
    }
    private void tableKhachHang() {
        PromptSupport.setPrompt("Nhập số điện thoại", txtTimKH);
        tableKH.getTableHeader().setFont(new Font("Cambria", Font.PLAIN, 16));
        tableKH.getTableHeader().setOpaque(false);
        tableKH.getTableHeader().setBackground(new Color(32, 136, 203));
        tableKH.getTableHeader().setForeground(new Color(255, 255, 255));
        tableKH.getColumnModel().getColumn(4).setCellEditor(new JDateChooserCellEditor());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        GD_KhachHang = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTimKH = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        radioNu1 = new javax.swing.JRadioButton();
        radioNam1 = new javax.swing.JRadioButton();
        ngaySinh1 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        btnLamMoi2 = new javax.swing.JButton();
        btnXoa2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKH = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        GD_KhachHang.setBackground(new java.awt.Color(255, 255, 255));
        GD_KhachHang.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        GD_KhachHang.setMaximumSize(new java.awt.Dimension(1200, 520));
        GD_KhachHang.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jPanel3.setMaximumSize(new java.awt.Dimension(1200, 300));
        jPanel3.setMinimumSize(new java.awt.Dimension(1200, 300));
        jPanel3.setPreferredSize(new java.awt.Dimension(1200, 300));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0};
        jPanel3Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel3.setLayout(jPanel3Layout);

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel4.setText("Mã khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jLabel4, gridBagConstraints);

        jTextField1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jTextField1.setEnabled(false);
        jTextField1.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextField1.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jTextField1, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel5.setText("Họ khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel3.add(jLabel5, gridBagConstraints);

        jTextField2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jTextField2.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextField2.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel3.add(jTextField2, gridBagConstraints);

        jTextField3.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jTextField3.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextField3.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel3.add(jTextField3, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel7.setText("Số điện thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel7, gridBagConstraints);

        jTextField4.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jTextField4.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextField4.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        jPanel3.add(jTextField4, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(121, 188, 215));
        jButton2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search-user.png"))); // NOI18N
        jButton2.setText("Tìm");
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jButton2, gridBagConstraints);

        jButton3.setBackground(new java.awt.Color(102, 255, 51));
        jButton3.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/system-update.png"))); // NOI18N
        jButton3.setText("Cập nhật thông tin");
        jButton3.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        jPanel3.add(jButton3, gridBagConstraints);

        jButton4.setBackground(new java.awt.Color(61, 102, 255));
        jButton4.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add-user.png"))); // NOI18N
        jButton4.setText("Thêm khách hàng");
        jButton4.setPreferredSize(new java.awt.Dimension(200, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        jPanel3.add(jButton4, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel8.setText("Tên khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel8, gridBagConstraints);

        jLabel9.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel9.setText("CCCD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel9, gridBagConstraints);

        txtTimKH.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTimKH.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        jPanel3.add(txtTimKH, gridBagConstraints);

        jLabel10.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel10.setText("Ngày sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel10, gridBagConstraints);

        jTextField6.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jTextField6.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        jPanel3.add(jTextField6, gridBagConstraints);

        radioNu1.setBackground(new java.awt.Color(255, 255, 255));
        radioNu1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        radioNu1.setText("Nữ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        jPanel3.add(radioNu1, gridBagConstraints);

        radioNam1.setBackground(new java.awt.Color(255, 255, 255));
        radioNam1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        radioNam1.setText("Nam");
        radioNam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNam1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(radioNam1, gridBagConstraints);

        ngaySinh1.setBackground(new java.awt.Color(255, 255, 255));
        ngaySinh1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ngaySinh1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        ngaySinh1.setMaximumSize(new java.awt.Dimension(250, 30));
        ngaySinh1.setMinimumSize(new java.awt.Dimension(250, 30));
        ngaySinh1.setPreferredSize(new java.awt.Dimension(185, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        jPanel3.add(ngaySinh1, gridBagConstraints);

        jLabel11.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel11.setText("Giới tính");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel11, gridBagConstraints);

        btnLamMoi2.setBackground(new java.awt.Color(0, 255, 153));
        btnLamMoi2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnLamMoi2.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        btnLamMoi2.setText("Làm mới");
        btnLamMoi2.setMaximumSize(new java.awt.Dimension(70, 40));
        btnLamMoi2.setMinimumSize(new java.awt.Dimension(70, 30));
        btnLamMoi2.setPreferredSize(new java.awt.Dimension(130, 30));
        btnLamMoi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoi2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(btnLamMoi2, gridBagConstraints);

        btnXoa2.setBackground(new java.awt.Color(204, 204, 204));
        btnXoa2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnXoa2.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eraser.png"))); // NOI18N
        btnXoa2.setText("Xóa trắng");
        btnXoa2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoa2.setMaximumSize(new java.awt.Dimension(120, 40));
        btnXoa2.setMinimumSize(new java.awt.Dimension(70, 30));
        btnXoa2.setPreferredSize(new java.awt.Dimension(130, 30));
        btnXoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(btnXoa2, gridBagConstraints);

        GD_KhachHang.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jPanel7.setMinimumSize(new java.awt.Dimension(1200, 220));
        jPanel7.setPreferredSize(new java.awt.Dimension(1200, 220));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N
        jScrollPane1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1200, 600));

        tableKH.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        tableKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "CCCD", "Họ", "Tên", "Ngày sinh", "Giới tính", "Số điện thoại"
            }
        ));
        tableKH.setPreferredSize(new java.awt.Dimension(1200, 600));
        tableKH.setRowHeight(25);
        jScrollPane1.setViewportView(tableKH);

        jPanel7.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        GD_KhachHang.add(jPanel7, java.awt.BorderLayout.CENTER);

        add(GD_KhachHang, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void radioNam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNam1ActionPerformed

    private void btnLamMoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoi2ActionPerformed

    private void btnXoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoa2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GD_KhachHang;
    private javax.swing.JButton btnLamMoi2;
    private javax.swing.JButton btnXoa2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private com.toedter.calendar.JDateChooser ngaySinh1;
    private javax.swing.JRadioButton radioNam1;
    private javax.swing.JRadioButton radioNu1;
    private javax.swing.JTable tableKH;
    private javax.swing.JTextField txtTimKH;
    // End of variables declaration//GEN-END:variables
}
