/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JDateChooserCellEditor;
import java.awt.Color;
import java.awt.Font;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author PC BAO THONG
 */
public class GD_NhanVien extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachNhanVien
     */
    public GD_NhanVien() {
        initComponents();
        setTitle("Quản lý nhân viên");
        //setResizable(false);
        setLocationRelativeTo(null);
        PromptSupport.setPrompt("Nhập số điện thoại", txtTim);
        table();
    }

    private void table() {
        tableDSNV.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 18));
        tableDSNV.getTableHeader().setOpaque(false);
        tableDSNV.getTableHeader().setBackground(new Color(32, 136, 203));
        tableDSNV.getTableHeader().setForeground(new Color(255, 255, 255));
        //chức vụ
        String[] chucvu = {"Quản lý", "Lễ tân", "Bảo vệ", "Phục vụ"};
        JComboBox comboBoxCV = new JComboBox(chucvu);
        comboBoxCV.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        comboBoxCV.setBackground(new Color(255, 255, 255));
        tableDSNV.getColumnModel().getColumn(9).setCellEditor(new DefaultCellEditor(comboBoxCV));
        //giới tính
        String[] gioitinh = {"Nam", "Nữ"};
        JComboBox comboBoxGT = new JComboBox(gioitinh);
        comboBoxGT.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        comboBoxGT.setBackground(new Color(255, 255, 255));
        tableDSNV.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(comboBoxGT));
        //trạng thái
        String[] trangthai = {"Đang làm", "Đã nghỉ"};
        JComboBox comboBoxTT = new JComboBox(trangthai);
        comboBoxTT.setFont(new Font("Segoe UI", Font.PLAIN, 18));
        comboBoxTT.setBackground(new Color(255, 255, 255));
        tableDSNV.getColumnModel().getColumn(11).setCellEditor(new DefaultCellEditor(comboBoxTT));
        //ngày sinh
        tableDSNV.getColumnModel().getColumn(4).setCellEditor(new JDateChooserCellEditor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        panelHeader = new javax.swing.JPanel();
        panelL = new javax.swing.JPanel();
        panelC = new javax.swing.JPanel();
        lblTittle = new javax.swing.JLabel();
        panelR = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        panelDSNV = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        tableDSNV = new javax.swing.JTable();
        panelCenter = new javax.swing.JPanel();
        lblMaNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        lblCCCD = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        lblHo = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        lblTen = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        ngaySinh = new com.toedter.calendar.JDateChooser();
        lblGioiTinh = new javax.swing.JLabel();
        radioNam = new javax.swing.JRadioButton();
        radioNu = new javax.swing.JRadioButton();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtChucVu = new javax.swing.JLabel();
        comboChucVu = new javax.swing.JComboBox<>();
        lblMatKhau = new javax.swing.JLabel();
        pwMatKhau = new javax.swing.JPasswordField();
        lblTrangThai = new javax.swing.JLabel();
        radioDangLam = new javax.swing.JRadioButton();
        radioDaNghi = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnDoi = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelHeader.setBackground(new java.awt.Color(255, 255, 255));
        panelHeader.setPreferredSize(new java.awt.Dimension(1200, 40));
        panelHeader.setLayout(new java.awt.GridLayout(1, 0));

        panelL.setBackground(new java.awt.Color(121, 188, 215));

        javax.swing.GroupLayout panelLLayout = new javax.swing.GroupLayout(panelL);
        panelL.setLayout(panelLLayout);
        panelLLayout.setHorizontalGroup(
            panelLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLLayout.setVerticalGroup(
            panelLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        panelHeader.add(panelL);

        panelC.setBackground(new java.awt.Color(121, 188, 215));
        panelC.setLayout(new java.awt.GridBagLayout());

        lblTittle.setBackground(new java.awt.Color(255, 255, 255));
        lblTittle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTittle.setForeground(new java.awt.Color(33, 36, 71));
        lblTittle.setText("QUẢN LÝ NHÂN VIÊN");
        lblTittle.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        panelC.add(lblTittle, new java.awt.GridBagConstraints());

        panelHeader.add(panelC);

        panelR.setBackground(new java.awt.Color(121, 188, 215));
        panelR.setPreferredSize(new java.awt.Dimension(300, 40));
        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {0, 10, 0};
        jPanel4Layout.rowHeights = new int[] {0};
        panelR.setLayout(jPanel4Layout);

        lblUser.setBackground(new java.awt.Color(255, 255, 255));
        lblUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N
        lblUser.setText("Quản lý - Đặng Bảo Thông");
        lblUser.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        panelR.add(lblUser, gridBagConstraints);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        btnLogout.setBorder(null);
        btnLogout.setContentAreaFilled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        panelR.add(btnLogout, gridBagConstraints);

        panelHeader.add(panelR);

        getContentPane().add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelDSNV.setBackground(new java.awt.Color(255, 255, 255));
        panelDSNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelDSNV.setLayout(new java.awt.BorderLayout());

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        tableDSNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableDSNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "CCCD", "Họ", "Tên", "Ngày sinh", "Giới tính", "Số điện thoại", "Email", "Địa chỉ", "Chức vụ", "Mật khẩu", "Trạng thái"
            }
        ));
        tableDSNV.setRowHeight(25);
        tableDSNV.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tableDSNV.setShowHorizontalLines(true);
        tableDSNV.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(tableDSNV);

        panelDSNV.add(scrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelDSNV, java.awt.BorderLayout.SOUTH);

        panelCenter.setBackground(new java.awt.Color(255, 255, 255));
        panelCenter.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0, 22, 0};
        jPanel1Layout.rowHeights = new int[] {0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0, 20, 0};
        panelCenter.setLayout(jPanel1Layout);

        lblMaNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMaNV.setText("Mã nhân viên");
        lblMaNV.setMaximumSize(new java.awt.Dimension(110, 40));
        lblMaNV.setMinimumSize(new java.awt.Dimension(110, 40));
        lblMaNV.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblMaNV, gridBagConstraints);

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMaNV.setEnabled(false);
        txtMaNV.setMaximumSize(new java.awt.Dimension(250, 40));
        txtMaNV.setMinimumSize(new java.awt.Dimension(250, 40));
        txtMaNV.setPreferredSize(new java.awt.Dimension(250, 40));
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        panelCenter.add(txtMaNV, gridBagConstraints);

        lblCCCD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCCCD.setText("Căn cước công dân");
        lblCCCD.setMaximumSize(new java.awt.Dimension(155, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblCCCD, gridBagConstraints);

        txtCCCD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCCCD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCCCD.setMaximumSize(new java.awt.Dimension(250, 40));
        txtCCCD.setMinimumSize(new java.awt.Dimension(250, 40));
        txtCCCD.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        panelCenter.add(txtCCCD, gridBagConstraints);

        lblHo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHo.setText("Họ nhân viên");
        lblHo.setMaximumSize(new java.awt.Dimension(110, 40));
        lblHo.setMinimumSize(new java.awt.Dimension(110, 40));
        lblHo.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblHo, gridBagConstraints);

        txtHo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHo.setMaximumSize(new java.awt.Dimension(250, 40));
        txtHo.setMinimumSize(new java.awt.Dimension(250, 40));
        txtHo.setPreferredSize(new java.awt.Dimension(250, 40));
        txtHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        panelCenter.add(txtHo, gridBagConstraints);

        lblTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTen.setText("Tên nhân viên");
        lblTen.setMaximumSize(new java.awt.Dimension(110, 40));
        lblTen.setMinimumSize(new java.awt.Dimension(110, 40));
        lblTen.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblTen, gridBagConstraints);

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTen.setMaximumSize(new java.awt.Dimension(250, 40));
        txtTen.setMinimumSize(new java.awt.Dimension(250, 40));
        txtTen.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        panelCenter.add(txtTen, gridBagConstraints);

        lblNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNgaySinh.setText("Ngày sinh");
        lblNgaySinh.setMaximumSize(new java.awt.Dimension(110, 40));
        lblNgaySinh.setMinimumSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblNgaySinh, gridBagConstraints);

        ngaySinh.setBackground(new java.awt.Color(255, 255, 255));
        ngaySinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ngaySinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ngaySinh.setMaximumSize(new java.awt.Dimension(250, 40));
        ngaySinh.setMinimumSize(new java.awt.Dimension(250, 40));
        ngaySinh.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        panelCenter.add(ngaySinh, gridBagConstraints);

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGioiTinh.setText("Giới tính");
        lblGioiTinh.setMaximumSize(new java.awt.Dimension(110, 40));
        lblGioiTinh.setMinimumSize(new java.awt.Dimension(110, 40));
        lblGioiTinh.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblGioiTinh, gridBagConstraints);

        radioNam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioNam);
        radioNam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radioNam.setText("Nam");
        radioNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNamActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(radioNam, gridBagConstraints);

        radioNu.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(radioNu);
        radioNu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radioNu.setText("Nữ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        panelCenter.add(radioNu, gridBagConstraints);

        lblSDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSDT.setText("Số điện thoại");
        lblSDT.setMaximumSize(new java.awt.Dimension(110, 40));
        lblSDT.setMinimumSize(new java.awt.Dimension(110, 40));
        lblSDT.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblSDT, gridBagConstraints);

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSDT.setMaximumSize(new java.awt.Dimension(250, 40));
        txtSDT.setMinimumSize(new java.awt.Dimension(250, 40));
        txtSDT.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        panelCenter.add(txtSDT, gridBagConstraints);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmail.setText("Email");
        lblEmail.setMaximumSize(new java.awt.Dimension(110, 40));
        lblEmail.setMinimumSize(new java.awt.Dimension(110, 40));
        lblEmail.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblEmail, gridBagConstraints);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmail.setMaximumSize(new java.awt.Dimension(250, 40));
        txtEmail.setMinimumSize(new java.awt.Dimension(250, 40));
        txtEmail.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        panelCenter.add(txtEmail, gridBagConstraints);

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDiaChi.setText("Địa chỉ");
        lblDiaChi.setMaximumSize(new java.awt.Dimension(110, 40));
        lblDiaChi.setMinimumSize(new java.awt.Dimension(110, 40));
        lblDiaChi.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblDiaChi, gridBagConstraints);

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDiaChi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDiaChi.setMaximumSize(new java.awt.Dimension(250, 40));
        txtDiaChi.setMinimumSize(new java.awt.Dimension(250, 40));
        txtDiaChi.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        panelCenter.add(txtDiaChi, gridBagConstraints);

        txtChucVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtChucVu.setText("Chức vụ");
        txtChucVu.setMaximumSize(new java.awt.Dimension(110, 40));
        txtChucVu.setMinimumSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(txtChucVu, gridBagConstraints);

        comboChucVu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Lễ tân", "Bảo vệ", "Phục vụ" }));
        comboChucVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboChucVu.setMaximumSize(new java.awt.Dimension(250, 40));
        comboChucVu.setMinimumSize(new java.awt.Dimension(250, 40));
        comboChucVu.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        panelCenter.add(comboChucVu, gridBagConstraints);

        lblMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMatKhau.setText("Mật khẩu");
        lblMatKhau.setMaximumSize(new java.awt.Dimension(110, 40));
        lblMatKhau.setMinimumSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblMatKhau, gridBagConstraints);

        pwMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pwMatKhau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pwMatKhau.setMaximumSize(new java.awt.Dimension(250, 40));
        pwMatKhau.setMinimumSize(new java.awt.Dimension(250, 40));
        pwMatKhau.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        panelCenter.add(pwMatKhau, gridBagConstraints);

        lblTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTrangThai.setText("Trạng thái");
        lblTrangThai.setMaximumSize(new java.awt.Dimension(110, 40));
        lblTrangThai.setMinimumSize(new java.awt.Dimension(110, 40));
        lblTrangThai.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(lblTrangThai, gridBagConstraints);

        radioDangLam.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(radioDangLam);
        radioDangLam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radioDangLam.setText("Đang làm");
        radioDangLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDangLamActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(radioDangLam, gridBagConstraints);

        radioDaNghi.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(radioDaNghi);
        radioDaNghi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        radioDaNghi.setText("Đã nghỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        panelCenter.add(radioDaNghi, gridBagConstraints);

        btnThem.setBackground(new java.awt.Color(51, 102, 255));
        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add-user.png"))); // NOI18N
        btnThem.setText("Thêm nhân viên");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(btnThem, gridBagConstraints);

        btnCapNhat.setBackground(new java.awt.Color(102, 255, 51));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/system-update.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật thông tin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        panelCenter.add(btnCapNhat, gridBagConstraints);

        btnDoi.setBackground(new java.awt.Color(255, 51, 51));
        btnDoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDoi.setForeground(new java.awt.Color(255, 255, 255));
        btnDoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/change.png"))); // NOI18N
        btnDoi.setText("Đổi trạng thái");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(btnDoi, gridBagConstraints);

        btnTim.setBackground(new java.awt.Color(121, 188, 215));
        btnTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search-user.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        panelCenter.add(btnTim, gridBagConstraints);

        txtTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTim.setMaximumSize(new java.awt.Dimension(250, 40));
        txtTim.setMinimumSize(new java.awt.Dimension(250, 40));
        txtTim.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        panelCenter.add(txtTim, gridBagConstraints);

        btnLamMoi.setBackground(new java.awt.Color(0, 255, 153));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        panelCenter.add(btnLamMoi, gridBagConstraints);

        btnXoa.setBackground(new java.awt.Color(204, 204, 204));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eraser.png"))); // NOI18N
        btnXoa.setText("Xóa trắng");
        btnXoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoa.setMaximumSize(new java.awt.Dimension(127, 32));
        btnXoa.setMinimumSize(new java.awt.Dimension(127, 32));
        btnXoa.setPreferredSize(new java.awt.Dimension(127, 32));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelCenter.add(btnXoa, gridBagConstraints);

        getContentPane().add(panelCenter, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoActionPerformed

    private void radioNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNamActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void radioDangLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDangLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDangLamActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_NhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GD_NhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDoi;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> comboChucVu;
    private javax.swing.JLabel lblCCCD;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHo;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JLabel lblUser;
    private com.toedter.calendar.JDateChooser ngaySinh;
    private javax.swing.JPanel panelC;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelDSNV;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelL;
    private javax.swing.JPanel panelR;
    private javax.swing.JPasswordField pwMatKhau;
    private javax.swing.JRadioButton radioDaNghi;
    private javax.swing.JRadioButton radioDangLam;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioNu;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tableDSNV;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JLabel txtChucVu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
