/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.toedter.calendar.JDateChooserCellEditor;
import java.awt.Color;
import java.awt.Font;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author PC BAO THONG
 */
public class GD_PhieuDP extends javax.swing.JPanel {

    /**
     * Creates new form GD_PhieuDP
     */
    public GD_PhieuDP() {
        initComponents();
        tablePhieuDat();
    }

    private void tablePhieuDat() {
        PromptSupport.setPrompt("Nhập số điện thoại khách", txtTimPhieu);
        tablePhieu.getTableHeader().setFont(new Font("Cambria", Font.PLAIN, 16));
        tablePhieu.getTableHeader().setOpaque(false);
        tablePhieu.getTableHeader().setBackground(new Color(32, 136, 203));
        tablePhieu.getTableHeader().setForeground(new Color(255, 255, 255));
        tablePhieu.getColumnModel().getColumn(3).setCellEditor(new JDateChooserCellEditor());
        tablePhieu.getColumnModel().getColumn(4).setCellEditor(new JDateChooserCellEditor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        GD_PhieuDatPhong = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePhieu = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField10 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        txtTimPhieu = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        GD_PhieuDatPhong.setBackground(new java.awt.Color(255, 255, 255));
        GD_PhieuDatPhong.setLayout(new java.awt.BorderLayout());

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phiếu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N
        jPanel16.setMinimumSize(new java.awt.Dimension(1200, 220));
        jPanel16.setPreferredSize(new java.awt.Dimension(1200, 220));
        jPanel16.setLayout(new java.awt.BorderLayout());

        tablePhieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu", "Tên khách hàng", "Số điện thoại", "Thời gian đặt", "Thời gian nhận", "Tên nhân viên", "Trạng thái phiếu"
            }
        ));
        tablePhieu.setRowHeight(25);
        jScrollPane2.setViewportView(tablePhieu);

        jPanel16.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        GD_PhieuDatPhong.add(jPanel16, java.awt.BorderLayout.CENTER);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phiếu đặt phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N
        jPanel15.setMinimumSize(new java.awt.Dimension(1200, 300));
        jPanel15.setPreferredSize(new java.awt.Dimension(1200, 300));
        java.awt.GridBagLayout jPanel15Layout = new java.awt.GridBagLayout();
        jPanel15Layout.columnWidths = new int[] {0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0, 15, 0};
        jPanel15Layout.rowHeights = new int[] {0, 20, 0, 20, 0, 20, 0};
        jPanel15.setLayout(jPanel15Layout);

        jComboBox4.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chờ nhận phòng", "Đã nhận" }));
        jComboBox4.setMinimumSize(new java.awt.Dimension(200, 30));
        jComboBox4.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel15.add(jComboBox4, gridBagConstraints);

        jTextField10.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jTextField10.setEnabled(false);
        jTextField10.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextField10.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel15.add(jTextField10, gridBagConstraints);

        jTextField9.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jTextField9.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextField9.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 2;
        jPanel15.add(jTextField9, gridBagConstraints);

        txtTimPhieu.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTimPhieu.setMinimumSize(new java.awt.Dimension(200, 30));
        txtTimPhieu.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel15.add(txtTimPhieu, gridBagConstraints);

        jTextField7.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jTextField7.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextField7.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        jPanel15.add(jTextField7, gridBagConstraints);

        jLabel26.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel26.setText("Trạng thái phiếu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel15.add(jLabel26, gridBagConstraints);

        jLabel25.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel25.setText("Thời gian nhận");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel15.add(jLabel25, gridBagConstraints);

        jLabel24.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel24.setText("Thời gian đặt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel15.add(jLabel24, gridBagConstraints);

        jLabel23.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel23.setText("Mã phiếu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel15.add(jLabel23, gridBagConstraints);

        jLabel22.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel22.setText("Tên nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel15.add(jLabel22, gridBagConstraints);

        jLabel21.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel21.setText("Tên khách hàng");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel15.add(jLabel21, gridBagConstraints);

        jLabel20.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel20.setText("Số điện thoại");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel15.add(jLabel20, gridBagConstraints);

        jDateChooser1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jDateChooser1.setMinimumSize(new java.awt.Dimension(200, 30));
        jDateChooser1.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        jPanel15.add(jDateChooser1, gridBagConstraints);

        jDateChooser2.setEnabled(false);
        jDateChooser2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jDateChooser2.setMinimumSize(new java.awt.Dimension(200, 30));
        jDateChooser2.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel15.add(jDateChooser2, gridBagConstraints);

        jButton14.setBackground(new java.awt.Color(121, 188, 215));
        jButton14.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search-doc.png"))); // NOI18N
        jButton14.setText("Tìm");
        jButton14.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton14.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel15.add(jButton14, gridBagConstraints);

        jButton15.setBackground(new java.awt.Color(0, 204, 204));
        jButton15.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/paper.png"))); // NOI18N
        jButton15.setText("Xem chi tiết");
        jButton15.setMinimumSize(new java.awt.Dimension(150, 30));
        jButton15.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel15.add(jButton15, gridBagConstraints);

        jButton16.setBackground(new java.awt.Color(0, 255, 213));
        jButton16.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        jButton16.setText("Làm mới");
        jButton16.setMinimumSize(new java.awt.Dimension(120, 30));
        jButton16.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel15.add(jButton16, gridBagConstraints);

        jTextField11.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jTextField11.setMinimumSize(new java.awt.Dimension(200, 30));
        jTextField11.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel15.add(jTextField11, gridBagConstraints);

        jButton20.setBackground(new java.awt.Color(102, 255, 51));
        jButton20.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/system-update.png"))); // NOI18N
        jButton20.setText("Cập nhật");
        jButton20.setMinimumSize(new java.awt.Dimension(120, 30));
        jButton20.setPreferredSize(new java.awt.Dimension(150, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        jPanel15.add(jButton20, gridBagConstraints);

        GD_PhieuDatPhong.add(jPanel15, java.awt.BorderLayout.PAGE_START);

        add(GD_PhieuDatPhong, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GD_PhieuDatPhong;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton20;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable tablePhieu;
    private javax.swing.JTextField txtTimPhieu;
    // End of variables declaration//GEN-END:variables
}
