/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.toedter.calendar.JDateChooserCellEditor;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.PopupMenu;
import javax.swing.DefaultCellEditor;
import javax.swing.Icon;
import javax.swing.JComboBox;
import javax.swing.JMenuItem;
import javax.swing.SwingConstants;
import org.jdesktop.swingx.plaf.PromptTextUI;
import org.jdesktop.swingx.prompt.PromptSupport;

/**
 *
 * @author PC BAO THONG
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public GiaoDienChinh() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Quản lý karaoke NNice");
        GD_DichVu.setVisible(false);
        tableDichVu();
        tableNhanVien();
    }

    private void tableDichVu() {
        PromptSupport.setPrompt("Nhập mã dịch vụ", txtTim);
        tableDichVu.getTableHeader().setFont(new Font("Cambria", Font.PLAIN, 16));
        tableDichVu.getTableHeader().setOpaque(false);
        tableDichVu.getTableHeader().setBackground(new Color(32, 136, 203));
        tableDichVu.getTableHeader().setForeground(new Color(255, 255, 255));
        //đơn vị bán
        String[] donVi = {"Lon", "Cái", "Đĩa", "Hộp"};
        JComboBox comboBoxDV = new JComboBox(donVi);
        comboBoxDV.setFont(new Font("Cambria", Font.PLAIN, 16));
        comboBoxDV.setBackground(new Color(255, 255, 255));
        tableDichVu.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(comboBoxDV));
        //xuất xứ
        String[] xuatXu = {"Việt Nam", "Thái Lan", "Trung Quốc", "Hoa Kỳ", "Đức"};
        JComboBox comboBoxXX = new JComboBox(xuatXu);
        comboBoxXX.setFont(new Font("Cambria", Font.PLAIN, 16));
        comboBoxXX.setBackground(new Color(255, 255, 255));
        tableDichVu.getColumnModel().getColumn(6).setCellEditor(new DefaultCellEditor(comboBoxXX));
        //tình trạng
        String[] tinhTrang = {"Đang bán", "Ngừng bán"};
        JComboBox comboBoxTT = new JComboBox(tinhTrang);
        comboBoxTT.setFont(new Font("Cambria", Font.PLAIN, 16));
        comboBoxTT.setBackground(new Color(255, 255, 255));
        tableDichVu.getColumnModel().getColumn(7).setCellEditor(new DefaultCellEditor(comboBoxTT));
        //HSD
        tableDichVu.getColumnModel().getColumn(5).setCellEditor(new JDateChooserCellEditor());
    }

    private void tableNhanVien() {
        tableDSNV.getTableHeader().setFont(new Font("Cambria", Font.PLAIN, 16));
        tableDSNV.getTableHeader().setOpaque(false);
        tableDSNV.getTableHeader().setBackground(new Color(32, 136, 203));
        tableDSNV.getTableHeader().setForeground(new Color(255, 255, 255));
        //chức vụ
        String[] chucvu = {"Quản lý", "Lễ tân", "Bảo vệ", "Phục vụ"};
        JComboBox comboBoxCV = new JComboBox(chucvu);
        comboBoxCV.setFont(new Font("Cambria", Font.PLAIN, 16));
        comboBoxCV.setBackground(new Color(255, 255, 255));
        tableDSNV.getColumnModel().getColumn(9).setCellEditor(new DefaultCellEditor(comboBoxCV));
        //giới tính
        String[] gioitinh = {"Nam", "Nữ"};
        JComboBox comboBoxGT = new JComboBox(gioitinh);
        comboBoxGT.setFont(new Font("Cambria", Font.PLAIN, 16));
        comboBoxGT.setBackground(new Color(255, 255, 255));
        tableDSNV.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(comboBoxGT));
        //trạng thái
        String[] trangthai = {"Đang làm", "Đã nghỉ"};
        JComboBox comboBoxTT = new JComboBox(trangthai);
        comboBoxTT.setFont(new Font("Cambria", Font.PLAIN, 16));
        comboBoxTT.setBackground(new Color(255, 255, 255));
        tableDSNV.getColumnModel().getColumn(11).setCellEditor(new DefaultCellEditor(comboBoxTT));
        //ngày sinh
        tableDSNV.getColumnModel().getColumn(4).setCellEditor(new JDateChooserCellEditor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        GD_DichVu = new javax.swing.JPanel();
        panelNorth = new javax.swing.JPanel();
        lblMaDV = new javax.swing.JLabel();
        txtMaDV = new javax.swing.JTextField();
        lblDonGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        lblTenDV = new javax.swing.JLabel();
        txtTenDV = new javax.swing.JTextField();
        lblHsd = new javax.swing.JLabel();
        hsd = new com.toedter.calendar.JDateChooser();
        lblXuatXu = new javax.swing.JLabel();
        comboXuatXu = new javax.swing.JComboBox<>();
        lblDonViBan = new javax.swing.JLabel();
        comboDVB = new javax.swing.JComboBox<>();
        lblSoLuong = new javax.swing.JLabel();
        spinSoLuong = new com.toedter.components.JSpinField();
        lblTinhTrang = new javax.swing.JLabel();
        radioDangBan = new javax.swing.JRadioButton();
        radioNgungBan = new javax.swing.JRadioButton();
        btnThemDV = new javax.swing.JButton();
        btnCapNhatDV = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        panelCenter = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        tableDichVu = new javax.swing.JTable();
        GD_NhanVien = new javax.swing.JPanel();
        panelNorth1 = new javax.swing.JPanel();
        lblMaNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        lblCCCD = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        lblHo = new javax.swing.JLabel();
        txtHo = new javax.swing.JTextField();
        lblTen = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        lblNgaySinh = new javax.swing.JLabel();
        ngaySinh = new com.toedter.calendar.JDateChooser();
        lblGioiTinh = new javax.swing.JLabel();
        radioNam = new javax.swing.JRadioButton();
        radioNu = new javax.swing.JRadioButton();
        lblSDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtChucVu = new javax.swing.JLabel();
        comboChucVu = new javax.swing.JComboBox<>();
        lblMatKhau = new javax.swing.JLabel();
        pwMatKhau = new javax.swing.JPasswordField();
        lblTrangThai = new javax.swing.JLabel();
        radioDangLam = new javax.swing.JRadioButton();
        radioDaNghi = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnTim1 = new javax.swing.JButton();
        txtTim1 = new javax.swing.JTextField();
        btnLamMoi1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        panelDSNV = new javax.swing.JPanel();
        scrollPane1 = new javax.swing.JScrollPane();
        tableDSNV = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();

        GD_DichVu.setMaximumSize(new java.awt.Dimension(1200, 820));
        GD_DichVu.setMinimumSize(new java.awt.Dimension(1200, 820));
        GD_DichVu.setPreferredSize(new java.awt.Dimension(1200, 820));
        GD_DichVu.setLayout(new java.awt.BorderLayout());

        panelNorth.setBackground(new java.awt.Color(255, 255, 255));
        panelNorth.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N
        panelNorth.setMaximumSize(new java.awt.Dimension(1200, 320));
        panelNorth.setMinimumSize(new java.awt.Dimension(1200, 320));
        panelNorth.setPreferredSize(new java.awt.Dimension(1200, 320));
        java.awt.GridBagLayout panelNorthLayout = new java.awt.GridBagLayout();
        panelNorthLayout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        panelNorthLayout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        panelNorth.setLayout(panelNorthLayout);

        lblMaDV.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblMaDV.setText("Mã dịch vụ");
        lblMaDV.setMaximumSize(new java.awt.Dimension(110, 40));
        lblMaDV.setMinimumSize(new java.awt.Dimension(110, 40));
        lblMaDV.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(lblMaDV, gridBagConstraints);

        txtMaDV.setBackground(new java.awt.Color(242, 242, 242));
        txtMaDV.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtMaDV.setText("DVB001");
        txtMaDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMaDV.setEnabled(false);
        txtMaDV.setMaximumSize(new java.awt.Dimension(250, 40));
        txtMaDV.setMinimumSize(new java.awt.Dimension(250, 40));
        txtMaDV.setPreferredSize(new java.awt.Dimension(250, 40));
        txtMaDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        panelNorth.add(txtMaDV, gridBagConstraints);

        lblDonGia.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblDonGia.setText("Đơn giá");
        lblDonGia.setMaximumSize(new java.awt.Dimension(155, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(lblDonGia, gridBagConstraints);

        txtDonGia.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtDonGia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDonGia.setMaximumSize(new java.awt.Dimension(250, 40));
        txtDonGia.setMinimumSize(new java.awt.Dimension(250, 40));
        txtDonGia.setPreferredSize(new java.awt.Dimension(250, 40));
        txtDonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDonGiaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        panelNorth.add(txtDonGia, gridBagConstraints);

        lblTenDV.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblTenDV.setText("Tên dịch vụ");
        lblTenDV.setMaximumSize(new java.awt.Dimension(110, 40));
        lblTenDV.setMinimumSize(new java.awt.Dimension(110, 40));
        lblTenDV.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(lblTenDV, gridBagConstraints);

        txtTenDV.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTenDV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTenDV.setMaximumSize(new java.awt.Dimension(250, 40));
        txtTenDV.setMinimumSize(new java.awt.Dimension(250, 40));
        txtTenDV.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        panelNorth.add(txtTenDV, gridBagConstraints);

        lblHsd.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblHsd.setText("Hạn sử dụng");
        lblHsd.setMaximumSize(new java.awt.Dimension(110, 40));
        lblHsd.setMinimumSize(new java.awt.Dimension(110, 40));
        lblHsd.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(lblHsd, gridBagConstraints);

        hsd.setBackground(new java.awt.Color(255, 255, 255));
        hsd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hsd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hsd.setMaximumSize(new java.awt.Dimension(250, 40));
        hsd.setMinimumSize(new java.awt.Dimension(250, 40));
        hsd.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 4;
        panelNorth.add(hsd, gridBagConstraints);

        lblXuatXu.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblXuatXu.setText("Xuất xứ");
        lblXuatXu.setMaximumSize(new java.awt.Dimension(110, 40));
        lblXuatXu.setMinimumSize(new java.awt.Dimension(110, 40));
        lblXuatXu.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(lblXuatXu, gridBagConstraints);

        comboXuatXu.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        comboXuatXu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Việt Nam", "Thái Lan", "Trung Quốc", "Hoa Kỳ", "Đức" }));
        comboXuatXu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboXuatXu.setMaximumSize(new java.awt.Dimension(250, 40));
        comboXuatXu.setMinimumSize(new java.awt.Dimension(250, 40));
        comboXuatXu.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 8;
        panelNorth.add(comboXuatXu, gridBagConstraints);

        lblDonViBan.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblDonViBan.setText("Đơn vị bán");
        lblDonViBan.setMaximumSize(new java.awt.Dimension(110, 40));
        lblDonViBan.setMinimumSize(new java.awt.Dimension(110, 40));
        lblDonViBan.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(lblDonViBan, gridBagConstraints);

        comboDVB.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        comboDVB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lon", "Cái", "Đĩa", "Hộp" }));
        comboDVB.setMaximumSize(new java.awt.Dimension(250, 40));
        comboDVB.setMinimumSize(new java.awt.Dimension(250, 40));
        comboDVB.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        panelNorth.add(comboDVB, gridBagConstraints);

        lblSoLuong.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblSoLuong.setText("Số lượng tồn");
        lblSoLuong.setMaximumSize(new java.awt.Dimension(110, 40));
        lblSoLuong.setMinimumSize(new java.awt.Dimension(110, 40));
        lblSoLuong.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(lblSoLuong, gridBagConstraints);

        spinSoLuong.setMaximumSize(new java.awt.Dimension(100, 40));
        spinSoLuong.setMinimum(0);
        spinSoLuong.setMinimumSize(new java.awt.Dimension(100, 40));
        spinSoLuong.setPreferredSize(new java.awt.Dimension(100, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(spinSoLuong, gridBagConstraints);

        lblTinhTrang.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblTinhTrang.setText("Tình trạng");
        lblTinhTrang.setMaximumSize(new java.awt.Dimension(110, 40));
        lblTinhTrang.setMinimumSize(new java.awt.Dimension(110, 40));
        lblTinhTrang.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(lblTinhTrang, gridBagConstraints);

        radioDangBan.setBackground(new java.awt.Color(255, 255, 255));
        radioDangBan.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        radioDangBan.setText("Đang bán");
        radioDangBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDangBanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(radioDangBan, gridBagConstraints);

        radioNgungBan.setBackground(new java.awt.Color(255, 255, 255));
        radioNgungBan.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        radioNgungBan.setText("Ngừng bán");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        panelNorth.add(radioNgungBan, gridBagConstraints);

        btnThemDV.setBackground(new java.awt.Color(51, 102, 255));
        btnThemDV.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnThemDV.setForeground(new java.awt.Color(255, 255, 255));
        btnThemDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add-user.png"))); // NOI18N
        btnThemDV.setText("Thêm dịch vụ");
        btnThemDV.setMaximumSize(new java.awt.Dimension(170, 40));
        btnThemDV.setMinimumSize(new java.awt.Dimension(170, 40));
        btnThemDV.setPreferredSize(new java.awt.Dimension(170, 40));
        btnThemDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(btnThemDV, gridBagConstraints);

        btnCapNhatDV.setBackground(new java.awt.Color(102, 255, 51));
        btnCapNhatDV.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnCapNhatDV.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhatDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/system-update.png"))); // NOI18N
        btnCapNhatDV.setText("Cập nhật thông tin");
        btnCapNhatDV.setMaximumSize(new java.awt.Dimension(210, 40));
        btnCapNhatDV.setMinimumSize(new java.awt.Dimension(210, 40));
        btnCapNhatDV.setPreferredSize(new java.awt.Dimension(210, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(btnCapNhatDV, gridBagConstraints);

        btnLamMoi.setBackground(new java.awt.Color(0, 255, 153));
        btnLamMoi.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setMaximumSize(new java.awt.Dimension(135, 40));
        btnLamMoi.setMinimumSize(new java.awt.Dimension(135, 40));
        btnLamMoi.setPreferredSize(new java.awt.Dimension(135, 40));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(btnLamMoi, gridBagConstraints);

        btnXoa.setBackground(new java.awt.Color(204, 204, 204));
        btnXoa.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eraser.png"))); // NOI18N
        btnXoa.setText("Xóa trắng");
        btnXoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoa.setMaximumSize(new java.awt.Dimension(135, 40));
        btnXoa.setMinimumSize(new java.awt.Dimension(135, 40));
        btnXoa.setPreferredSize(new java.awt.Dimension(135, 40));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 16;
        panelNorth.add(btnXoa, gridBagConstraints);

        btnTim.setBackground(new java.awt.Color(121, 188, 215));
        btnTim.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search-user.png"))); // NOI18N
        btnTim.setText("Tìm");
        btnTim.setMaximumSize(new java.awt.Dimension(95, 40));
        btnTim.setMinimumSize(new java.awt.Dimension(95, 40));
        btnTim.setPreferredSize(new java.awt.Dimension(95, 40));
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth.add(btnTim, gridBagConstraints);

        txtTim.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTim.setMaximumSize(new java.awt.Dimension(250, 40));
        txtTim.setMinimumSize(new java.awt.Dimension(250, 40));
        txtTim.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        panelNorth.add(txtTim, gridBagConstraints);

        GD_DichVu.add(panelNorth, java.awt.BorderLayout.PAGE_START);

        panelCenter.setBackground(new java.awt.Color(255, 255, 255));
        panelCenter.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        panelCenter.setMaximumSize(new java.awt.Dimension(1200, 500));
        panelCenter.setMinimumSize(new java.awt.Dimension(1200, 500));
        panelCenter.setPreferredSize(new java.awt.Dimension(1200, 500));
        panelCenter.setLayout(new java.awt.BorderLayout());

        scrollPane.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N
        scrollPane.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        scrollPane.setMaximumSize(new java.awt.Dimension(1200, 400));
        scrollPane.setMinimumSize(new java.awt.Dimension(1200, 400));
        scrollPane.setPreferredSize(new java.awt.Dimension(1200, 400));

        tableDichVu.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        tableDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Đơn vị bán", "Số lượng tồn", "Đơn giá", "Hạn sử dụng", "Xuất xứ", "Tình trạng"
            }
        ));
        tableDichVu.setRowHeight(25);
        tableDichVu.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tableDichVu.setShowHorizontalLines(true);
        tableDichVu.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(tableDichVu);
        if (tableDichVu.getColumnModel().getColumnCount() > 0) {
            tableDichVu.getColumnModel().getColumn(0).setResizable(false);
            tableDichVu.getColumnModel().getColumn(0).setPreferredWidth(20);
            tableDichVu.getColumnModel().getColumn(1).setResizable(false);
            tableDichVu.getColumnModel().getColumn(1).setPreferredWidth(100);
            tableDichVu.getColumnModel().getColumn(2).setResizable(false);
            tableDichVu.getColumnModel().getColumn(2).setPreferredWidth(0);
            tableDichVu.getColumnModel().getColumn(3).setResizable(false);
            tableDichVu.getColumnModel().getColumn(3).setPreferredWidth(0);
            tableDichVu.getColumnModel().getColumn(4).setResizable(false);
            tableDichVu.getColumnModel().getColumn(4).setPreferredWidth(100);
            tableDichVu.getColumnModel().getColumn(5).setResizable(false);
            tableDichVu.getColumnModel().getColumn(5).setPreferredWidth(150);
            tableDichVu.getColumnModel().getColumn(6).setResizable(false);
            tableDichVu.getColumnModel().getColumn(6).setPreferredWidth(60);
            tableDichVu.getColumnModel().getColumn(7).setResizable(false);
            tableDichVu.getColumnModel().getColumn(7).setPreferredWidth(60);
        }

        panelCenter.add(scrollPane, java.awt.BorderLayout.CENTER);

        GD_DichVu.add(panelCenter, java.awt.BorderLayout.CENTER);

        GD_NhanVien.setMaximumSize(new java.awt.Dimension(1200, 820));
        GD_NhanVien.setLayout(new java.awt.BorderLayout());

        panelNorth1.setBackground(new java.awt.Color(255, 255, 255));
        panelNorth1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N
        panelNorth1.setMaximumSize(new java.awt.Dimension(1200, 320));
        panelNorth1.setMinimumSize(new java.awt.Dimension(1200, 320));
        panelNorth1.setPreferredSize(new java.awt.Dimension(1200, 320));
        java.awt.GridBagLayout panelNorth1Layout = new java.awt.GridBagLayout();
        panelNorth1Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        panelNorth1Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        panelNorth1.setLayout(panelNorth1Layout);

        lblMaNV.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblMaNV.setText("Mã nhân viên");
        lblMaNV.setMaximumSize(new java.awt.Dimension(110, 40));
        lblMaNV.setMinimumSize(new java.awt.Dimension(110, 40));
        lblMaNV.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(lblMaNV, gridBagConstraints);

        txtMaNV.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtMaNV.setText("NV001");
        txtMaNV.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMaNV.setEnabled(false);
        txtMaNV.setMaximumSize(new java.awt.Dimension(150, 40));
        txtMaNV.setMinimumSize(new java.awt.Dimension(150, 40));
        txtMaNV.setPreferredSize(new java.awt.Dimension(150, 40));
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        panelNorth1.add(txtMaNV, gridBagConstraints);

        lblCCCD.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblCCCD.setText("Căn cước công dân");
        lblCCCD.setMaximumSize(new java.awt.Dimension(155, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(lblCCCD, gridBagConstraints);

        txtCCCD.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtCCCD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCCCD.setMaximumSize(new java.awt.Dimension(185, 185));
        txtCCCD.setMinimumSize(new java.awt.Dimension(150, 40));
        txtCCCD.setPreferredSize(new java.awt.Dimension(185, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        panelNorth1.add(txtCCCD, gridBagConstraints);

        lblHo.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblHo.setText("Họ nhân viên");
        lblHo.setMaximumSize(new java.awt.Dimension(110, 40));
        lblHo.setMinimumSize(new java.awt.Dimension(110, 40));
        lblHo.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(lblHo, gridBagConstraints);

        txtHo.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtHo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHo.setMaximumSize(new java.awt.Dimension(150, 40));
        txtHo.setMinimumSize(new java.awt.Dimension(150, 40));
        txtHo.setPreferredSize(new java.awt.Dimension(150, 40));
        txtHo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        panelNorth1.add(txtHo, gridBagConstraints);

        lblTen.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblTen.setText("Tên nhân viên");
        lblTen.setMaximumSize(new java.awt.Dimension(110, 40));
        lblTen.setMinimumSize(new java.awt.Dimension(110, 40));
        lblTen.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(lblTen, gridBagConstraints);

        txtTen.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTen.setMaximumSize(new java.awt.Dimension(185, 185));
        txtTen.setMinimumSize(new java.awt.Dimension(150, 40));
        txtTen.setPreferredSize(new java.awt.Dimension(185, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        panelNorth1.add(txtTen, gridBagConstraints);

        lblNgaySinh.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblNgaySinh.setText("Ngày sinh");
        lblNgaySinh.setMaximumSize(new java.awt.Dimension(110, 40));
        lblNgaySinh.setMinimumSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(lblNgaySinh, gridBagConstraints);

        ngaySinh.setBackground(new java.awt.Color(255, 255, 255));
        ngaySinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ngaySinh.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        ngaySinh.setMaximumSize(new java.awt.Dimension(250, 40));
        ngaySinh.setMinimumSize(new java.awt.Dimension(250, 40));
        ngaySinh.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        panelNorth1.add(ngaySinh, gridBagConstraints);

        lblGioiTinh.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblGioiTinh.setText("Giới tính");
        lblGioiTinh.setMaximumSize(new java.awt.Dimension(110, 40));
        lblGioiTinh.setMinimumSize(new java.awt.Dimension(110, 40));
        lblGioiTinh.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(lblGioiTinh, gridBagConstraints);

        radioNam.setBackground(new java.awt.Color(255, 255, 255));
        radioNam.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        radioNam.setText("Nam");
        radioNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNamActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(radioNam, gridBagConstraints);

        radioNu.setBackground(new java.awt.Color(255, 255, 255));
        radioNu.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        radioNu.setText("Nữ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        panelNorth1.add(radioNu, gridBagConstraints);

        lblSDT.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblSDT.setText("Số điện thoại");
        lblSDT.setMaximumSize(new java.awt.Dimension(110, 40));
        lblSDT.setMinimumSize(new java.awt.Dimension(110, 40));
        lblSDT.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(lblSDT, gridBagConstraints);

        txtSDT.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtSDT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSDT.setMaximumSize(new java.awt.Dimension(150, 40));
        txtSDT.setMinimumSize(new java.awt.Dimension(150, 40));
        txtSDT.setPreferredSize(new java.awt.Dimension(150, 40));
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        panelNorth1.add(txtSDT, gridBagConstraints);

        lblEmail.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblEmail.setText("Email");
        lblEmail.setMaximumSize(new java.awt.Dimension(110, 40));
        lblEmail.setMinimumSize(new java.awt.Dimension(110, 40));
        lblEmail.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(lblEmail, gridBagConstraints);

        txtEmail.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmail.setMaximumSize(new java.awt.Dimension(250, 40));
        txtEmail.setMinimumSize(new java.awt.Dimension(250, 40));
        txtEmail.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        panelNorth1.add(txtEmail, gridBagConstraints);

        lblDiaChi.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblDiaChi.setText("Địa chỉ");
        lblDiaChi.setMaximumSize(new java.awt.Dimension(110, 40));
        lblDiaChi.setMinimumSize(new java.awt.Dimension(110, 40));
        lblDiaChi.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(lblDiaChi, gridBagConstraints);

        txtDiaChi.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtDiaChi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDiaChi.setMaximumSize(new java.awt.Dimension(250, 40));
        txtDiaChi.setMinimumSize(new java.awt.Dimension(250, 40));
        txtDiaChi.setPreferredSize(new java.awt.Dimension(250, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        panelNorth1.add(txtDiaChi, gridBagConstraints);

        txtChucVu.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtChucVu.setText("Chức vụ");
        txtChucVu.setMaximumSize(new java.awt.Dimension(110, 40));
        txtChucVu.setMinimumSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(txtChucVu, gridBagConstraints);

        comboChucVu.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        comboChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Lễ tân", "Bảo vệ", "Phục vụ" }));
        comboChucVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        comboChucVu.setMaximumSize(new java.awt.Dimension(150, 40));
        comboChucVu.setMinimumSize(new java.awt.Dimension(150, 40));
        comboChucVu.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        panelNorth1.add(comboChucVu, gridBagConstraints);

        lblMatKhau.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblMatKhau.setText("Mật khẩu");
        lblMatKhau.setMaximumSize(new java.awt.Dimension(110, 40));
        lblMatKhau.setMinimumSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(lblMatKhau, gridBagConstraints);

        pwMatKhau.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        pwMatKhau.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pwMatKhau.setMaximumSize(new java.awt.Dimension(185, 185));
        pwMatKhau.setMinimumSize(new java.awt.Dimension(150, 40));
        pwMatKhau.setPreferredSize(new java.awt.Dimension(185, 40));
        pwMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwMatKhauActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        panelNorth1.add(pwMatKhau, gridBagConstraints);

        lblTrangThai.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        lblTrangThai.setText("Trạng thái");
        lblTrangThai.setMaximumSize(new java.awt.Dimension(110, 40));
        lblTrangThai.setMinimumSize(new java.awt.Dimension(110, 40));
        lblTrangThai.setPreferredSize(new java.awt.Dimension(110, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(lblTrangThai, gridBagConstraints);

        radioDangLam.setBackground(new java.awt.Color(255, 255, 255));
        radioDangLam.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        radioDangLam.setText("Đang làm");
        radioDangLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDangLamActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(radioDangLam, gridBagConstraints);

        radioDaNghi.setBackground(new java.awt.Color(255, 255, 255));
        radioDaNghi.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        radioDaNghi.setText("Đã nghỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        panelNorth1.add(radioDaNghi, gridBagConstraints);

        btnThem.setBackground(new java.awt.Color(51, 102, 255));
        btnThem.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add-user.png"))); // NOI18N
        btnThem.setText("Thêm nhân viên");
        btnThem.setMaximumSize(new java.awt.Dimension(180, 40));
        btnThem.setMinimumSize(new java.awt.Dimension(180, 40));
        btnThem.setPreferredSize(new java.awt.Dimension(180, 40));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(btnThem, gridBagConstraints);

        btnCapNhat.setBackground(new java.awt.Color(102, 255, 51));
        btnCapNhat.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/system-update.png"))); // NOI18N
        btnCapNhat.setText("Cập nhật thông tin");
        btnCapNhat.setMaximumSize(new java.awt.Dimension(190, 40));
        btnCapNhat.setMinimumSize(new java.awt.Dimension(190, 40));
        btnCapNhat.setPreferredSize(new java.awt.Dimension(190, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        panelNorth1.add(btnCapNhat, gridBagConstraints);

        btnTim1.setBackground(new java.awt.Color(121, 188, 215));
        btnTim1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnTim1.setForeground(new java.awt.Color(255, 255, 255));
        btnTim1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search-user.png"))); // NOI18N
        btnTim1.setText("Tìm");
        btnTim1.setMaximumSize(new java.awt.Dimension(90, 40));
        btnTim1.setMinimumSize(new java.awt.Dimension(90, 40));
        btnTim1.setPreferredSize(new java.awt.Dimension(90, 40));
        btnTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(btnTim1, gridBagConstraints);

        txtTim1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        txtTim1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTim1.setMaximumSize(new java.awt.Dimension(150, 40));
        txtTim1.setMinimumSize(new java.awt.Dimension(150, 40));
        txtTim1.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        panelNorth1.add(txtTim1, gridBagConstraints);

        btnLamMoi1.setBackground(new java.awt.Color(0, 255, 153));
        btnLamMoi1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnLamMoi1.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/refresh.png"))); // NOI18N
        btnLamMoi1.setText("Làm mới");
        btnLamMoi1.setMaximumSize(new java.awt.Dimension(70, 40));
        btnLamMoi1.setMinimumSize(new java.awt.Dimension(70, 40));
        btnLamMoi1.setPreferredSize(new java.awt.Dimension(130, 40));
        btnLamMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoi1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(btnLamMoi1, gridBagConstraints);

        btnXoa1.setBackground(new java.awt.Color(204, 204, 204));
        btnXoa1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        btnXoa1.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eraser.png"))); // NOI18N
        btnXoa1.setText("Xóa trắng");
        btnXoa1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnXoa1.setMaximumSize(new java.awt.Dimension(120, 40));
        btnXoa1.setMinimumSize(new java.awt.Dimension(120, 40));
        btnXoa1.setPreferredSize(new java.awt.Dimension(120, 40));
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        panelNorth1.add(btnXoa1, gridBagConstraints);

        GD_NhanVien.add(panelNorth1, java.awt.BorderLayout.PAGE_START);

        panelDSNV.setBackground(new java.awt.Color(255, 255, 255));
        panelDSNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        panelDSNV.setMaximumSize(new java.awt.Dimension(1200, 500));
        panelDSNV.setMinimumSize(new java.awt.Dimension(1200, 500));
        panelDSNV.setPreferredSize(new java.awt.Dimension(1200, 500));
        panelDSNV.setLayout(new java.awt.BorderLayout());

        scrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        scrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Cambria", 0, 16))); // NOI18N

        tableDSNV.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        tableDSNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "CCCD", "Họ", "Tên", "Ngày sinh", "Giới tính", "Số điện thoại", "Email", "Địa chỉ", "Chức vụ", "Mật khẩu", "Trạng thái"
            }
        ));
        tableDSNV.setRowHeight(25);
        tableDSNV.setSelectionBackground(new java.awt.Color(204, 255, 255));
        tableDSNV.setShowHorizontalLines(true);
        tableDSNV.getTableHeader().setReorderingAllowed(false);
        scrollPane1.setViewportView(tableDSNV);
        if (tableDSNV.getColumnModel().getColumnCount() > 0) {
            tableDSNV.getColumnModel().getColumn(0).setResizable(false);
            tableDSNV.getColumnModel().getColumn(0).setPreferredWidth(15);
            tableDSNV.getColumnModel().getColumn(1).setResizable(false);
            tableDSNV.getColumnModel().getColumn(1).setPreferredWidth(20);
            tableDSNV.getColumnModel().getColumn(2).setResizable(false);
            tableDSNV.getColumnModel().getColumn(2).setPreferredWidth(50);
            tableDSNV.getColumnModel().getColumn(3).setResizable(false);
            tableDSNV.getColumnModel().getColumn(3).setPreferredWidth(100);
            tableDSNV.getColumnModel().getColumn(4).setResizable(false);
            tableDSNV.getColumnModel().getColumn(5).setResizable(false);
            tableDSNV.getColumnModel().getColumn(5).setPreferredWidth(20);
            tableDSNV.getColumnModel().getColumn(6).setResizable(false);
            tableDSNV.getColumnModel().getColumn(7).setResizable(false);
            tableDSNV.getColumnModel().getColumn(7).setPreferredWidth(0);
            tableDSNV.getColumnModel().getColumn(8).setResizable(false);
            tableDSNV.getColumnModel().getColumn(8).setPreferredWidth(0);
            tableDSNV.getColumnModel().getColumn(9).setResizable(false);
            tableDSNV.getColumnModel().getColumn(9).setPreferredWidth(20);
            tableDSNV.getColumnModel().getColumn(10).setResizable(false);
            tableDSNV.getColumnModel().getColumn(10).setPreferredWidth(20);
            tableDSNV.getColumnModel().getColumn(11).setResizable(false);
            tableDSNV.getColumnModel().getColumn(11).setPreferredWidth(20);
        }

        panelDSNV.add(scrollPane1, java.awt.BorderLayout.CENTER);

        GD_NhanVien.add(panelDSNV, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(121, 188, 215));
        setMinimumSize(new java.awt.Dimension(1200, 900));
        setSize(new java.awt.Dimension(1200, 900));

        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 900));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(1200, 40));
        jPanel2.setMinimumSize(new java.awt.Dimension(1200, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 40));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBackground(new java.awt.Color(121, 188, 215));
        jPanel6.setMaximumSize(new java.awt.Dimension(400, 40));
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 40));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        jPanel5.setBackground(new java.awt.Color(121, 188, 215));
        jPanel5.setMaximumSize(new java.awt.Dimension(400, 40));
        jPanel5.setMinimumSize(new java.awt.Dimension(400, 40));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 40));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel2.setText("TRANG CHỦ");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel5.add(jLabel2, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel5);

        jPanel4.setBackground(new java.awt.Color(121, 188, 215));
        jPanel4.setMaximumSize(new java.awt.Dimension(400, 40));
        jPanel4.setMinimumSize(new java.awt.Dimension(400, 40));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 40));
        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {0, 5, 0};
        jPanel4Layout.rowHeights = new int[] {0};
        jPanel4.setLayout(jPanel4Layout);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N
        jLabel3.setText("Quản lý - Đặng Bảo Thông");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jLabel3, gridBagConstraints);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jButton1, gridBagConstraints);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(1200, 820));
        jPanel3.setMinimumSize(new java.awt.Dimension(1200, 820));
        jPanel3.setPreferredSize(new java.awt.Dimension(1200, 820));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home.png"))); // NOI18N
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jMenuBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar2.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jMenuBar2.setMaximumSize(new java.awt.Dimension(1200, 3276840));
        jMenuBar2.setMinimumSize(new java.awt.Dimension(1200, 40));
        jMenuBar2.setPreferredSize(new java.awt.Dimension(1200, 40));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/house.png"))); // NOI18N
        jMenu1.setText("Trang chủ");
        jMenu1.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu1);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon_nv.png"))); // NOI18N
        jMenu4.setText("Nhân viên");
        jMenu4.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/people.png"))); // NOI18N
        jMenu5.setText("Khách hàng");
        jMenu5.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jMenuBar2.add(jMenu5);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/food.png"))); // NOI18N
        jMenu10.setText("Dịch vụ");
        jMenu10.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu10MouseClicked(evt);
            }
        });
        jMenu10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu10ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu10);

        jMenu11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/building.png"))); // NOI18N
        jMenu11.setText("Phòng");
        jMenu11.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jMenu11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu11ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu11);

        jMenu12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/invoice.png"))); // NOI18N
        jMenu12.setText("Hóa đơn");
        jMenu12.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jMenuBar2.add(jMenu12);

        jMenu13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bar-chart.png"))); // NOI18N
        jMenu13.setText("Thống kê");
        jMenu13.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        jMenuBar2.add(jMenu13);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenu11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu11ActionPerformed

    private void jMenu10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu10ActionPerformed

    }//GEN-LAST:event_jMenu10ActionPerformed

    private void jMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu10MouseClicked
        // TODO add your handling code here:
        jPanel3.setVisible(false);
        jLabel2.setText("QUẢN LÝ DỊCH VỤ");
        jPanel1.add(GD_DichVu, BorderLayout.CENTER);
        GD_DichVu.setVisible(true);
    }//GEN-LAST:event_jMenu10MouseClicked

    private void txtMaDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDVActionPerformed

    private void txtDonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDonGiaActionPerformed

    private void radioDangBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDangBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDangBanActionPerformed

    private void btnThemDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemDVActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTimActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        jPanel3.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void txtHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoActionPerformed

    private void radioNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioNamActionPerformed

    private void radioDangLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDangLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDangLamActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTim1ActionPerformed

    private void btnLamMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoi1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        GD_DichVu.setVisible(false);
        GD_NhanVien.setVisible(true);
        jLabel2.setText("QUẢN LÝ NHÂN VIÊN");
        jPanel1.add(GD_NhanVien, BorderLayout.CENTER);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void pwMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GD_DichVu;
    private javax.swing.JPanel GD_NhanVien;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnCapNhatDV;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLamMoi1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemDV;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTim1;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JComboBox<String> comboChucVu;
    private javax.swing.JComboBox<String> comboDVB;
    private javax.swing.JComboBox<String> comboXuatXu;
    private com.toedter.calendar.JDateChooser hsd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblCCCD;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblDonGia;
    private javax.swing.JLabel lblDonViBan;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHo;
    private javax.swing.JLabel lblHsd;
    private javax.swing.JLabel lblMaDV;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTenDV;
    private javax.swing.JLabel lblTinhTrang;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JLabel lblXuatXu;
    private com.toedter.calendar.JDateChooser ngaySinh;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelDSNV;
    private javax.swing.JPanel panelNorth;
    private javax.swing.JPanel panelNorth1;
    private javax.swing.JPasswordField pwMatKhau;
    private javax.swing.JRadioButton radioDaNghi;
    private javax.swing.JRadioButton radioDangBan;
    private javax.swing.JRadioButton radioDangLam;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioNgungBan;
    private javax.swing.JRadioButton radioNu;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JScrollPane scrollPane1;
    private com.toedter.components.JSpinField spinSoLuong;
    private javax.swing.JTable tableDSNV;
    private javax.swing.JTable tableDichVu;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JLabel txtChucVu;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMaDV;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenDV;
    private javax.swing.JTextField txtTim;
    private javax.swing.JTextField txtTim1;
    // End of variables declaration//GEN-END:variables

    private Object DSPhong() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
