/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import com.raven.chart.Chart;
import com.raven.chart.ModelChart;
import java.awt.Color;

/**
 *
 * @author PC BAO THONG
 */
public class ThongKeDoanhThuThang extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeDoanhThuThang
     */
    public ThongKeDoanhThuThang() {
        initComponents();
        chart.start();
        chart.addLegend("Tổng doanh thu", new Color(245, 189, 135));
        chart.addData(new ModelChart("January", new double[]{500000}));
        chart.addData(new ModelChart("February", new double[]{6000000, 750, 90, 150}));
        chart.addData(new ModelChart("March", new double[]{2000000, 350, 460, 900}));
        chart.addData(new ModelChart("April", new double[]{4800000, 150, 750, 700}));
        chart.addData(new ModelChart("May", new double[]{3500000, 540, 300, 150}));
        chart.addData(new ModelChart("June", new double[]{190000, 280, 81, 200}));
        chart.addData(new ModelChart("July", new double[]{5000000}));
        chart.addData(new ModelChart("August", new double[]{600000, 750, 90, 150}));
        chart.addData(new ModelChart("September", new double[]{200000, 350, 460, 900}));
        chart.addData(new ModelChart("October", new double[]{480000, 150, 750, 700}));
        chart.addData(new ModelChart("November", new double[]{350000, 540, 300, 150}));
        chart.addData(new ModelChart("December", new double[]{190000, 280, 81, 200}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chart = new com.raven.chart.Chart();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 520));

        chart.setPreferredSize(new java.awt.Dimension(900, 520));
        add(chart);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel1.setText("Năm");
        add(jLabel1);

        jComboBox1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.chart.Chart chart;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
